// src/prisma/seed.js — AZAMED Cameroun — Base médicale complète
const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');
const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Démarrage du seed AZAMED Cameroun...');

  // ADMIN
  const adminHash = await bcrypt.hash('Admin@AZAMED2024', 10);
  await prisma.user.upsert({
    where: { email: 'admin@azamed.com' },
    update: {},
    create: { email: 'admin@azamed.com', passwordHash: adminHash, role: 'ADMIN', isVerified: true },
  });
  console.log('✅ Admin : admin@azamed.com / Admin@AZAMED2024');

  // ══════════════════════════════════════════════════════════
  // MÉDICAMENTS
  // ══════════════════════════════════════════════════════════
  const medicaments = [
    // Analgésiques / Antipyrétiques
    { nomCommercial:'Paracétamol 500mg', dci:'Paracétamol', classeTherapeutique:'Analgésique/Antipyrétique', forme:'Comprimé', dosage:'500mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Paracétamol 1000mg', dci:'Paracétamol', classeTherapeutique:'Analgésique/Antipyrétique', forme:'Comprimé effervescent', dosage:'1000mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Paracétamol Sirop 120mg/5ml', dci:'Paracétamol', classeTherapeutique:'Analgésique/Antipyrétique pédiatrique', forme:'Sirop', dosage:'120mg/5ml', laboratoireFabricant:'Générique' },
    { nomCommercial:'Efferalgan 500mg', dci:'Paracétamol', classeTherapeutique:'Analgésique/Antipyrétique', forme:'Comprimé effervescent', dosage:'500mg', laboratoireFabricant:'UPSA' },
    { nomCommercial:'Doliprane 1000mg', dci:'Paracétamol', classeTherapeutique:'Analgésique/Antipyrétique', forme:'Comprimé', dosage:'1000mg', laboratoireFabricant:'Sanofi' },
    { nomCommercial:'Ibuprofène 200mg', dci:'Ibuprofène', classeTherapeutique:'AINS', forme:'Comprimé', dosage:'200mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Ibuprofène 400mg', dci:'Ibuprofène', classeTherapeutique:'AINS', forme:'Comprimé enrobé', dosage:'400mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Diclofénac 50mg', dci:'Diclofénac sodique', classeTherapeutique:'AINS', forme:'Comprimé gastrorésistant', dosage:'50mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Diclofénac 75mg Injectable', dci:'Diclofénac sodique', classeTherapeutique:'AINS Injectable', forme:'Solution injectable IM', dosage:'75mg/3ml', laboratoireFabricant:'Générique' },
    { nomCommercial:'Voltarène 50mg', dci:'Diclofénac sodique', classeTherapeutique:'AINS', forme:'Comprimé', dosage:'50mg', laboratoireFabricant:'Novartis' },
    { nomCommercial:'Aspirine 500mg', dci:'Acide acétylsalicylique', classeTherapeutique:'Analgésique/Antiagrégant', forme:'Comprimé', dosage:'500mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Aspirine 100mg (Cardio)', dci:'Acide acétylsalicylique', classeTherapeutique:'Antiagrégant plaquettaire', forme:'Comprimé gastrorésistant', dosage:'100mg', laboratoireFabricant:'Bayer' },
    { nomCommercial:'Tramadol 50mg', dci:'Tramadol', classeTherapeutique:'Analgésique opioïde faible', forme:'Gélule', dosage:'50mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Tramadol 100mg LP', dci:'Tramadol', classeTherapeutique:'Analgésique opioïde faible', forme:'Comprimé LP', dosage:'100mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Morphine 10mg Injectable', dci:'Morphine', classeTherapeutique:'Analgésique opioïde fort', forme:'Solution injectable', dosage:'10mg/ml', laboratoireFabricant:'Générique' },
    { nomCommercial:'Néfopam 20mg Injectable', dci:'Néfopam', classeTherapeutique:'Analgésique central', forme:'Solution injectable', dosage:'20mg/2ml', laboratoireFabricant:'Biocodex' },
    // Antipaludéens
    { nomCommercial:'Coartem 20/120mg', dci:'Artéméther+Luméfantrine', classeTherapeutique:'Antipaludéen - Combinaison', forme:'Comprimé', dosage:'20/120mg', laboratoireFabricant:'Novartis' },
    { nomCommercial:'Artéméther-Luméfantrine Générique', dci:'Artéméther+Luméfantrine', classeTherapeutique:'Antipaludéen - Combinaison', forme:'Comprimé', dosage:'20/120mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Artéméther-Luméfantrine Pédiatrique', dci:'Artéméther+Luméfantrine', classeTherapeutique:'Antipaludéen pédiatrique', forme:'Comprimé dispersible', dosage:'20/120mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Artésunate 50mg', dci:'Artésunate', classeTherapeutique:'Antipaludéen - Artémisinine', forme:'Comprimé', dosage:'50mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Artésunate 60mg Injectable', dci:'Artésunate', classeTherapeutique:'Antipaludéen grave Injectable', forme:'Poudre injectable', dosage:'60mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Quinine 300mg', dci:'Quinine', classeTherapeutique:'Antipaludéen - Quinoléine', forme:'Comprimé', dosage:'300mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Quinine 500mg Injectable', dci:'Quinine dichlorhydrate', classeTherapeutique:'Antipaludéen grave Injectable', forme:'Solution injectable IV', dosage:'500mg/2ml', laboratoireFabricant:'Générique' },
    { nomCommercial:'Chloroquine 100mg', dci:'Chloroquine', classeTherapeutique:'Antipaludéen/Antiinflammatoire', forme:'Comprimé', dosage:'100mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Sulfadoxine-Pyriméthamine (Fansidar)', dci:'Sulfadoxine+Pyriméthamine', classeTherapeutique:'Antipaludéen préventif TPI', forme:'Comprimé', dosage:'500/25mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Dihydroartémisinine-Pipéraquine', dci:'DHA+Pipéraquine', classeTherapeutique:'Antipaludéen - Combinaison', forme:'Comprimé', dosage:'40/320mg', laboratoireFabricant:'Générique' },
    // Antibiotiques
    { nomCommercial:'Amoxicilline 250mg', dci:'Amoxicilline', classeTherapeutique:'Antibiotique - Pénicilline', forme:'Gélule', dosage:'250mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Amoxicilline 500mg', dci:'Amoxicilline', classeTherapeutique:'Antibiotique - Pénicilline', forme:'Gélule', dosage:'500mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Amoxicilline 1g', dci:'Amoxicilline', classeTherapeutique:'Antibiotique - Pénicilline', forme:'Comprimé dispersible', dosage:'1g', laboratoireFabricant:'Générique' },
    { nomCommercial:'Amoxicilline Sirop 125mg/5ml', dci:'Amoxicilline', classeTherapeutique:'Antibiotique pédiatrique', forme:'Poudre pour sirop', dosage:'125mg/5ml', laboratoireFabricant:'Générique' },
    { nomCommercial:'Augmentin 500/125mg', dci:'Amoxicilline+Ac. clavulanique', classeTherapeutique:'Antibiotique - Pénicilline protégée', forme:'Comprimé', dosage:'500/125mg', laboratoireFabricant:'GSK' },
    { nomCommercial:'Augmentin 1g/125mg', dci:'Amoxicilline+Ac. clavulanique', classeTherapeutique:'Antibiotique - Pénicilline protégée', forme:'Comprimé', dosage:'1g/125mg', laboratoireFabricant:'GSK' },
    { nomCommercial:'Ampicilline 500mg', dci:'Ampicilline', classeTherapeutique:'Antibiotique - Pénicilline', forme:'Gélule', dosage:'500mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Ampicilline 1g Injectable', dci:'Ampicilline', classeTherapeutique:'Antibiotique - Pénicilline Injectable', forme:'Poudre injectable', dosage:'1g', laboratoireFabricant:'Générique' },
    { nomCommercial:'Benzathine Pénicilline 1,2MUI', dci:'Benzathine benzylpénicilline', classeTherapeutique:'Antibiotique - Pénicilline retard', forme:'Poudre injectable IM', dosage:'1 200 000 UI', laboratoireFabricant:'Générique' },
    { nomCommercial:'Pénicilline G 5MUI Injectable', dci:'Benzylpénicilline', classeTherapeutique:'Antibiotique - Pénicilline IV', forme:'Poudre injectable IV', dosage:'5 000 000 UI', laboratoireFabricant:'Générique' },
    { nomCommercial:'Cotrimoxazole 480mg', dci:'Sulfaméthoxazole+Triméthoprime', classeTherapeutique:'Antibiotique - Sulfonamide', forme:'Comprimé', dosage:'400/80mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Cotrimoxazole Forte 960mg', dci:'Sulfaméthoxazole+Triméthoprime', classeTherapeutique:'Antibiotique - Sulfonamide', forme:'Comprimé', dosage:'800/160mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Cotrimoxazole Sirop Pédiatrique', dci:'Sulfaméthoxazole+Triméthoprime', classeTherapeutique:'Antibiotique pédiatrique', forme:'Sirop', dosage:'200/40mg/5ml', laboratoireFabricant:'Générique' },
    { nomCommercial:'Métronidazole 250mg', dci:'Métronidazole', classeTherapeutique:'Antibiotique - Imidazolé', forme:'Comprimé', dosage:'250mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Métronidazole 500mg', dci:'Métronidazole', classeTherapeutique:'Antibiotique - Imidazolé', forme:'Comprimé', dosage:'500mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Flagyl 500mg', dci:'Métronidazole', classeTherapeutique:'Antibiotique - Imidazolé', forme:'Comprimé', dosage:'500mg', laboratoireFabricant:'Sanofi' },
    { nomCommercial:'Métronidazole 500mg Injectable', dci:'Métronidazole', classeTherapeutique:'Antibiotique - Imidazolé IV', forme:'Solution injectable IV', dosage:'500mg/100ml', laboratoireFabricant:'Générique' },
    { nomCommercial:'Ciprofloxacine 250mg', dci:'Ciprofloxacine', classeTherapeutique:'Antibiotique - Fluoroquinolone', forme:'Comprimé', dosage:'250mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Ciprofloxacine 500mg', dci:'Ciprofloxacine', classeTherapeutique:'Antibiotique - Fluoroquinolone', forme:'Comprimé', dosage:'500mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Ciprofloxacine 200mg Injectable', dci:'Ciprofloxacine', classeTherapeutique:'Antibiotique IV', forme:'Solution injectable IV', dosage:'200mg/100ml', laboratoireFabricant:'Générique' },
    { nomCommercial:'Doxycycline 100mg', dci:'Doxycycline', classeTherapeutique:'Antibiotique - Tétracycline', forme:'Gélule', dosage:'100mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Azithromycine 250mg', dci:'Azithromycine', classeTherapeutique:'Antibiotique - Macrolide', forme:'Gélule', dosage:'250mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Azithromycine 500mg', dci:'Azithromycine', classeTherapeutique:'Antibiotique - Macrolide', forme:'Comprimé', dosage:'500mg', laboratoireFabricant:'Générique (Zithromax)' },
    { nomCommercial:'Érythromycine 250mg', dci:'Érythromycine', classeTherapeutique:'Antibiotique - Macrolide', forme:'Comprimé', dosage:'250mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Clarithromycine 500mg', dci:'Clarithromycine', classeTherapeutique:'Antibiotique - Macrolide', forme:'Comprimé', dosage:'500mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Ceftriaxone 500mg Injectable', dci:'Ceftriaxone', classeTherapeutique:'Antibiotique - Céphalosporine 3G', forme:'Poudre injectable', dosage:'500mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Ceftriaxone 1g Injectable', dci:'Ceftriaxone', classeTherapeutique:'Antibiotique - Céphalosporine 3G', forme:'Poudre injectable', dosage:'1g', laboratoireFabricant:'Générique' },
    { nomCommercial:'Céfixime 200mg', dci:'Céfixime', classeTherapeutique:'Antibiotique - Céphalosporine 3G oral', forme:'Gélule', dosage:'200mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Gentamicine 80mg Injectable', dci:'Gentamicine', classeTherapeutique:'Antibiotique - Aminoside', forme:'Solution injectable IM/IV', dosage:'80mg/2ml', laboratoireFabricant:'Générique' },
    { nomCommercial:'Streptomycine 1g Injectable', dci:'Streptomycine', classeTherapeutique:'Antituberculeux / Aminoside', forme:'Poudre injectable IM', dosage:'1g', laboratoireFabricant:'Générique' },
    { nomCommercial:'Chloramphénicol 250mg', dci:'Chloramphénicol', classeTherapeutique:'Antibiotique - Phénicolé', forme:'Gélule', dosage:'250mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Nitrofurantoïne 100mg', dci:'Nitrofurantoïne', classeTherapeutique:'Antibiotique urinaire', forme:'Gélule', dosage:'100mg', laboratoireFabricant:'Générique' },
    // Antituberculeux
    { nomCommercial:'Isoniazide 100mg', dci:'Isoniazide', classeTherapeutique:'Antituberculeux', forme:'Comprimé', dosage:'100mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Rifampicine 150mg', dci:'Rifampicine', classeTherapeutique:'Antituberculeux', forme:'Gélule', dosage:'150mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Rifampicine 300mg', dci:'Rifampicine', classeTherapeutique:'Antituberculeux', forme:'Gélule', dosage:'300mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Pyrazinamide 500mg', dci:'Pyrazinamide', classeTherapeutique:'Antituberculeux', forme:'Comprimé', dosage:'500mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Éthambutol 400mg', dci:'Éthambutol', classeTherapeutique:'Antituberculeux', forme:'Comprimé', dosage:'400mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'RHZE Combinaison 4en1', dci:'Rifampicine+Isoniazide+Pyrazinamide+Éthambutol', classeTherapeutique:'Antituberculeux - Phase initiale', forme:'Comprimé', dosage:'150/75/400/275mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'RH Combinaison 2en1', dci:'Rifampicine+Isoniazide', classeTherapeutique:'Antituberculeux - Phase continuation', forme:'Comprimé', dosage:'150/75mg', laboratoireFabricant:'Générique' },
    // ARV / VIH
    { nomCommercial:'TDF+3TC+EFV (1ère ligne)', dci:'Ténofovir+Lamivudine+Efavirenz', classeTherapeutique:'Antirétroviral - 1ère ligne', forme:'Comprimé', dosage:'300/300/600mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'TDF+3TC+DTG (Recommandé OMS)', dci:'Ténofovir+Lamivudine+Dolutégravir', classeTherapeutique:'Antirétroviral - Recommandé', forme:'Comprimé', dosage:'300/300/50mg', laboratoireFabricant:'ViiV Healthcare' },
    { nomCommercial:'Zidovudine+Lamivudine (AZT+3TC)', dci:'Zidovudine+Lamivudine', classeTherapeutique:'Antirétroviral - INTI', forme:'Comprimé', dosage:'300/150mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Lopinavir+Ritonavir (Kaletra)', dci:'Lopinavir+Ritonavir', classeTherapeutique:'Antirétroviral - IP', forme:'Comprimé', dosage:'200/50mg', laboratoireFabricant:'AbbVie' },
    { nomCommercial:'Névirapine 200mg', dci:'Névirapine', classeTherapeutique:'Antirétroviral - INNTI', forme:'Comprimé', dosage:'200mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Aciclovir 200mg', dci:'Aciclovir', classeTherapeutique:'Antiviral - Herpès', forme:'Comprimé', dosage:'200mg', laboratoireFabricant:'Générique' },
    // Antiparasitaires / Antifongiques
    { nomCommercial:'Albendazole 400mg', dci:'Albendazole', classeTherapeutique:'Antiparasitaire - Anthelminthique', forme:'Comprimé', dosage:'400mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Mébendazole 100mg', dci:'Mébendazole', classeTherapeutique:'Antiparasitaire - Anthelminthique', forme:'Comprimé', dosage:'100mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Ivermectine 3mg (Mectizan)', dci:'Ivermectine', classeTherapeutique:'Antiparasitaire - Onchocercose/Gale', forme:'Comprimé', dosage:'3mg', laboratoireFabricant:'MSD' },
    { nomCommercial:'Praziquantel 600mg', dci:'Praziquantel', classeTherapeutique:'Antiparasitaire - Bilharziose', forme:'Comprimé', dosage:'600mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Fluconazole 150mg', dci:'Fluconazole', classeTherapeutique:'Antifongique - Azolé', forme:'Gélule', dosage:'150mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Fluconazole 200mg', dci:'Fluconazole', classeTherapeutique:'Antifongique - Azolé', forme:'Gélule', dosage:'200mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Kétoconazole 200mg', dci:'Kétoconazole', classeTherapeutique:'Antifongique - Azolé', forme:'Comprimé', dosage:'200mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Nystatine 500 000UI', dci:'Nystatine', classeTherapeutique:'Antifongique - Polyène oral', forme:'Comprimé', dosage:'500 000 UI', laboratoireFabricant:'Générique' },
    { nomCommercial:'Clotrimazole Crème 1%', dci:'Clotrimazole', classeTherapeutique:'Antifongique topique', forme:'Crème cutanée', dosage:'1%', laboratoireFabricant:'Générique' },
    { nomCommercial:'Clotrimazole Ovule 100mg', dci:'Clotrimazole', classeTherapeutique:'Antifongique vaginal', forme:'Ovule gynécologique', dosage:'100mg', laboratoireFabricant:'Générique' },
    // Cardiovasculaires
    { nomCommercial:'Amlodipine 5mg', dci:'Amlodipine', classeTherapeutique:'Antihypertenseur - Inhibiteur calcique', forme:'Comprimé', dosage:'5mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Amlodipine 10mg', dci:'Amlodipine', classeTherapeutique:'Antihypertenseur - Inhibiteur calcique', forme:'Comprimé', dosage:'10mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Nifédipine 20mg LP', dci:'Nifédipine', classeTherapeutique:'Antihypertenseur - Inhibiteur calcique', forme:'Comprimé LP', dosage:'20mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Captopril 25mg', dci:'Captopril', classeTherapeutique:'Antihypertenseur - IEC', forme:'Comprimé', dosage:'25mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Énalapril 10mg', dci:'Énalapril', classeTherapeutique:'Antihypertenseur - IEC', forme:'Comprimé', dosage:'10mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Losartan 50mg', dci:'Losartan', classeTherapeutique:'Antihypertenseur - ARA II', forme:'Comprimé', dosage:'50mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Losartan 100mg', dci:'Losartan', classeTherapeutique:'Antihypertenseur - ARA II', forme:'Comprimé', dosage:'100mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Hydrochlorothiazide 25mg', dci:'Hydrochlorothiazide', classeTherapeutique:'Diurétique thiazidique', forme:'Comprimé', dosage:'25mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Furosémide 40mg', dci:'Furosémide', classeTherapeutique:'Diurétique de l\'anse', forme:'Comprimé', dosage:'40mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Furosémide 20mg Injectable', dci:'Furosémide', classeTherapeutique:'Diurétique Injectable', forme:'Solution injectable IV', dosage:'20mg/2ml', laboratoireFabricant:'Générique' },
    { nomCommercial:'Spironolactone 25mg', dci:'Spironolactone', classeTherapeutique:'Diurétique antialdostérone', forme:'Comprimé', dosage:'25mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Aténolol 50mg', dci:'Aténolol', classeTherapeutique:'Antihypertenseur - Bêtabloquant', forme:'Comprimé', dosage:'50mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Bisoprolol 5mg', dci:'Bisoprolol', classeTherapeutique:'Antihypertenseur - Bêtabloquant', forme:'Comprimé', dosage:'5mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Méthyldopa 250mg', dci:'Méthyldopa', classeTherapeutique:'Antihypertenseur central - Grossesse', forme:'Comprimé', dosage:'250mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Digoxine 0,25mg', dci:'Digoxine', classeTherapeutique:'Cardiotonique - Insuffisance cardiaque', forme:'Comprimé', dosage:'0,25mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Atorvastatine 20mg', dci:'Atorvastatine', classeTherapeutique:'Hypolipémiant - Statine', forme:'Comprimé', dosage:'20mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Simvastatine 20mg', dci:'Simvastatine', classeTherapeutique:'Hypolipémiant - Statine', forme:'Comprimé', dosage:'20mg', laboratoireFabricant:'Générique' },
    // Diabète
    { nomCommercial:'Metformine 500mg', dci:'Metformine', classeTherapeutique:'Antidiabétique oral - Biguanide', forme:'Comprimé', dosage:'500mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Metformine 850mg', dci:'Metformine', classeTherapeutique:'Antidiabétique oral - Biguanide', forme:'Comprimé', dosage:'850mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Metformine 1000mg', dci:'Metformine', classeTherapeutique:'Antidiabétique oral - Biguanide', forme:'Comprimé', dosage:'1000mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Glibenclamide 5mg', dci:'Glibenclamide', classeTherapeutique:'Antidiabétique oral - Sulfonylurée', forme:'Comprimé', dosage:'5mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Gliclazide 80mg', dci:'Gliclazide', classeTherapeutique:'Antidiabétique oral - Sulfonylurée', forme:'Comprimé', dosage:'80mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Insuline Rapide (Actrapid) 100UI/ml', dci:'Insuline humaine régulière', classeTherapeutique:'Antidiabétique - Insuline rapide', forme:'Solution injectable SC/IV', dosage:'100UI/ml', laboratoireFabricant:'Novo Nordisk' },
    { nomCommercial:'Insuline NPH (Insulatard) 100UI/ml', dci:'Insuline isophane', classeTherapeutique:'Antidiabétique - Insuline intermédiaire', forme:'Solution injectable SC', dosage:'100UI/ml', laboratoireFabricant:'Novo Nordisk' },
    { nomCommercial:'Insuline Glargine (Lantus) 100UI/ml', dci:'Insuline glargine', classeTherapeutique:'Antidiabétique - Insuline lente', forme:'Solution injectable SC', dosage:'100UI/ml', laboratoireFabricant:'Sanofi' },
    // Gastro-entérologie
    { nomCommercial:'Oméprazole 20mg', dci:'Oméprazole', classeTherapeutique:'IPP - Anti-ulcéreux', forme:'Gélule gastrorésistante', dosage:'20mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Oméprazole 40mg Injectable', dci:'Oméprazole', classeTherapeutique:'IPP - Anti-ulcéreux IV', forme:'Poudre injectable IV', dosage:'40mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Pantoprazole 40mg', dci:'Pantoprazole', classeTherapeutique:'IPP - Anti-ulcéreux', forme:'Comprimé gastrorésistant', dosage:'40mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Métoclopramide 10mg', dci:'Métoclopramide', classeTherapeutique:'Antiémétique - Prokinétique', forme:'Comprimé', dosage:'10mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Ondansétron 4mg', dci:'Ondansétron', classeTherapeutique:'Antiémétique - Sétron', forme:'Comprimé', dosage:'4mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Lopéramide 2mg', dci:'Lopéramide', classeTherapeutique:'Antidiarrhéique', forme:'Gélule', dosage:'2mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'SRO Sachet OMS', dci:'Sels de réhydratation orale', classeTherapeutique:'Réhydratation - Diarrhées', forme:'Poudre pour solution orale', dosage:'Sachet OMS standard', laboratoireFabricant:'Générique' },
    { nomCommercial:'Smecta 3g', dci:'Diosmectite', classeTherapeutique:'Antidiarrhéique - Adsorbant', forme:'Poudre suspension orale', dosage:'3g', laboratoireFabricant:'Ipsen' },
    { nomCommercial:'Hyoscine 10mg (Buscopan)', dci:'Hyoscine butylbromide', classeTherapeutique:'Antispasmodique', forme:'Comprimé', dosage:'10mg', laboratoireFabricant:'Boehringer' },
    { nomCommercial:'Phloroglucinol 80mg (Spasfon)', dci:'Phloroglucinol', classeTherapeutique:'Antispasmodique', forme:'Comprimé', dosage:'80mg', laboratoireFabricant:'Générique' },
    // Pneumologie
    { nomCommercial:'Salbutamol 100mcg Spray (Ventoline)', dci:'Salbutamol', classeTherapeutique:'Bronchodilatateur - Bêta2', forme:'Aérosol doseur', dosage:'100mcg/bouffée', laboratoireFabricant:'GSK' },
    { nomCommercial:'Salbutamol 2mg Comprimé', dci:'Salbutamol', classeTherapeutique:'Bronchodilatateur - Bêta2 oral', forme:'Comprimé', dosage:'2mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Béclométasone 250mcg Spray', dci:'Béclométasone', classeTherapeutique:'Corticoïde inhalé - Asthme', forme:'Aérosol doseur', dosage:'250mcg/bouffée', laboratoireFabricant:'Générique' },
    { nomCommercial:'Prednisolone 5mg', dci:'Prednisolone', classeTherapeutique:'Corticoïde systémique', forme:'Comprimé', dosage:'5mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Prednisolone 20mg', dci:'Prednisolone', classeTherapeutique:'Corticoïde systémique', forme:'Comprimé', dosage:'20mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Dexaméthasone 4mg Injectable', dci:'Dexaméthasone', classeTherapeutique:'Corticoïde injectable', forme:'Solution injectable IV/IM', dosage:'4mg/ml', laboratoireFabricant:'Générique' },
    { nomCommercial:'Bromhexine 8mg', dci:'Bromhexine', classeTherapeutique:'Mucolytique', forme:'Comprimé', dosage:'8mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Acétylcystéine 200mg', dci:'Acétylcystéine', classeTherapeutique:'Mucolytique', forme:'Sachet effervescent', dosage:'200mg', laboratoireFabricant:'Générique' },
    // Neurologie / Psychiatrie
    { nomCommercial:'Diazépam 5mg', dci:'Diazépam', classeTherapeutique:'Anxiolytique - Benzodiazépine', forme:'Comprimé', dosage:'5mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Diazépam 10mg Injectable', dci:'Diazépam', classeTherapeutique:'Anticonvulsivant Injectable', forme:'Solution injectable IV/IM', dosage:'10mg/2ml', laboratoireFabricant:'Générique' },
    { nomCommercial:'Phénobarbital 100mg', dci:'Phénobarbital', classeTherapeutique:'Antiépileptique - Barbiturique', forme:'Comprimé', dosage:'100mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Carbamazépine 200mg', dci:'Carbamazépine', classeTherapeutique:'Antiépileptique', forme:'Comprimé', dosage:'200mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Valproate de sodium 200mg', dci:'Valproate de sodium', classeTherapeutique:'Antiépileptique', forme:'Comprimé gastrorésistant', dosage:'200mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Halopéridol 5mg', dci:'Halopéridol', classeTherapeutique:'Antipsychotique', forme:'Comprimé', dosage:'5mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Chlorpromazine 100mg', dci:'Chlorpromazine', classeTherapeutique:'Antipsychotique', forme:'Comprimé', dosage:'100mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Amitriptyline 25mg', dci:'Amitriptyline', classeTherapeutique:'Antidépresseur tricyclique', forme:'Comprimé', dosage:'25mg', laboratoireFabricant:'Générique' },
    // Hématologie / Vitamines
    { nomCommercial:'Sulfate ferreux 200mg', dci:'Sulfate ferreux', classeTherapeutique:'Antianémique - Fer', forme:'Comprimé', dosage:'200mg (65mg Fe)', laboratoireFabricant:'Générique' },
    { nomCommercial:'Fer + Acide folique (Grossesse)', dci:'Sulfate ferreux+Acide folique', classeTherapeutique:'Antianémique - Grossesse', forme:'Comprimé', dosage:'200/0,4mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Acide folique 5mg', dci:'Acide folique', classeTherapeutique:'Vitamine B9', forme:'Comprimé', dosage:'5mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Vitamine B12 Injectable', dci:'Cyanocobalamine', classeTherapeutique:'Vitamine B12 - Antianémique', forme:'Solution injectable IM', dosage:'1000mcg/ml', laboratoireFabricant:'Générique' },
    { nomCommercial:'Vitamine A 200 000UI', dci:'Rétinol', classeTherapeutique:'Vitamine A', forme:'Capsule molle', dosage:'200 000 UI', laboratoireFabricant:'Générique' },
    { nomCommercial:'Vitamine C 500mg', dci:'Acide ascorbique', classeTherapeutique:'Vitamine C', forme:'Comprimé effervescent', dosage:'500mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Vitamine D3 100 000UI', dci:'Cholécalciférol', classeTherapeutique:'Vitamine D - Rachitisme', forme:'Solution buvable', dosage:'100 000 UI/2ml', laboratoireFabricant:'Générique' },
    { nomCommercial:'Zinc 20mg (Pédiatrique)', dci:'Sulfate de zinc', classeTherapeutique:'Oligoélément - Diarrhée enfant', forme:'Comprimé dispersible', dosage:'20mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Calcium 500mg + Vitamine D3', dci:'Carbonate calcium+Cholécalciférol', classeTherapeutique:'Calcium - Ostéoporose', forme:'Comprimé à croquer', dosage:'500mg/400UI', laboratoireFabricant:'Générique' },
    // Maternité / Obstétrique
    { nomCommercial:'Ocytocine 10UI Injectable', dci:'Ocytocine', classeTherapeutique:'Utérotonique - Accouchement/HPP', forme:'Solution injectable IM/IV', dosage:'10 UI/ml', laboratoireFabricant:'Générique' },
    { nomCommercial:'Misoprostol 200mcg', dci:'Misoprostol', classeTherapeutique:'Utérotonique - Prévention HPP', forme:'Comprimé', dosage:'200mcg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Sulfate de magnésium Injectable', dci:'Sulfate de magnésium', classeTherapeutique:'Anticonvulsivant - Éclampsie', forme:'Solution injectable IV/IM', dosage:'500mg/ml', laboratoireFabricant:'Générique' },
    { nomCommercial:'Méthylergonovine 0,2mg Injectable', dci:'Méthylergonovine', classeTherapeutique:'Utérotonique - Hémorragie du post-partum', forme:'Solution injectable IM', dosage:'0,2mg/ml', laboratoireFabricant:'Générique' },
    { nomCommercial:'Progestérone 200mg (Utrogestan)', dci:'Progestérone micronisée', classeTherapeutique:'Progestatif - Menace avortement', forme:'Capsule vaginale/orale', dosage:'200mg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Contraceptif Oral COC 30/150', dci:'Éthinylestradiol+Lévonorgestrel', classeTherapeutique:'Contraceptif oral combiné', forme:'Comprimé', dosage:'30mcg/150mcg', laboratoireFabricant:'Générique' },
    { nomCommercial:'Cérazette (Progestatif seul)', dci:'Désogestrel', classeTherapeutique:'Contraceptif progestatif oral', forme:'Comprimé', dosage:'75mcg', laboratoireFabricant:'Organon' },
    { nomCommercial:'Depo-Provera Injectable', dci:'Médroxyprogestérone acétate', classeTherapeutique:'Contraceptif injectable 3 mois', forme:'Solution injectable IM', dosage:'150mg/ml', laboratoireFabricant:'Pfizer' },
    { nomCommercial:'Contraception urgence (Norlevo)', dci:'Lévonorgestrel', classeTherapeutique:'Contraceptif d\'urgence', forme:'Comprimé', dosage:'1,5mg', laboratoireFabricant:'Générique' },
    // Solutés de perfusion
    { nomCommercial:'Sérum physiologique NaCl 0,9% 500ml', dci:'Chlorure de sodium 0,9%', classeTherapeutique:'Soluté isotonique', forme:'Solution IV', dosage:'0,9%/500ml', laboratoireFabricant:'Générique' },
    { nomCommercial:'Ringer Lactate 500ml', dci:'Solution Ringer Lactate', classeTherapeutique:'Soluté de remplissage', forme:'Solution IV', dosage:'500ml', laboratoireFabricant:'Générique' },
    { nomCommercial:'Glucosé 5% 500ml', dci:'Glucose 5%', classeTherapeutique:'Soluté glucosé isotonique', forme:'Solution IV', dosage:'5%/500ml', laboratoireFabricant:'Générique' },
    { nomCommercial:'Glucosé 10% 500ml', dci:'Glucose 10%', classeTherapeutique:'Soluté glucosé hypertonique', forme:'Solution IV', dosage:'10%/500ml', laboratoireFabricant:'Générique' },
    // Urgences / Réanimation
    { nomCommercial:'Adrénaline 1mg Injectable', dci:'Épinéphrine', classeTherapeutique:'Sympathomimétique - Choc anaphylactique', forme:'Solution injectable IV/IM', dosage:'1mg/ml', laboratoireFabricant:'Générique' },
    { nomCommercial:'Atropine 1mg Injectable', dci:'Atropine', classeTherapeutique:'Anticholinergique - Bradycardie', forme:'Solution injectable', dosage:'1mg/ml', laboratoireFabricant:'Générique' },
    { nomCommercial:'Gluconate de calcium 10% Injectable', dci:'Gluconate de calcium', classeTherapeutique:'Calcium IV - Hypocalcémie', forme:'Solution injectable IV lente', dosage:'10%/10ml', laboratoireFabricant:'Générique' },
    { nomCommercial:'Dopamine 200mg Injectable', dci:'Dopamine', classeTherapeutique:'Vasopresseur - État de choc', forme:'Solution injectable IV', dosage:'200mg/5ml', laboratoireFabricant:'Générique' },
    { nomCommercial:'Kétamine 500mg Injectable', dci:'Kétamine', classeTherapeutique:'Anesthésique - Analgésie', forme:'Solution injectable IV/IM', dosage:'500mg/10ml', laboratoireFabricant:'Générique' },
    { nomCommercial:'Naloxone 0,4mg Injectable', dci:'Naloxone', classeTherapeutique:'Antagoniste opioïde - Surdosage', forme:'Solution injectable', dosage:'0,4mg/ml', laboratoireFabricant:'Générique' },
    // Ophtalmologie / Dermatologie
    { nomCommercial:'Tétracycline Pommade Ophtalmique 1%', dci:'Tétracycline', classeTherapeutique:'Antibiotique ophtalmique - Trachome', forme:'Pommade ophtalmique', dosage:'1%', laboratoireFabricant:'Générique' },
    { nomCommercial:'Chloramphénicol Collyre 0,5%', dci:'Chloramphénicol', classeTherapeutique:'Antibiotique ophtalmique', forme:'Collyre', dosage:'0,5%', laboratoireFabricant:'Générique' },
    { nomCommercial:'Perméthrine Crème 5% (Gale)', dci:'Perméthrine', classeTherapeutique:'Antiparasitaire cutané', forme:'Crème', dosage:'5%', laboratoireFabricant:'Générique' },
    { nomCommercial:'Bétadine 10% Solution', dci:'Povidone iodée', classeTherapeutique:'Antiseptique large spectre', forme:'Solution cutanée', dosage:'10%', laboratoireFabricant:'MEDA Pharma' },
    { nomCommercial:'Alcool 70° Isopropylique', dci:'Alcool isopropylique', classeTherapeutique:'Antiseptique cutané', forme:'Solution', dosage:'70°', laboratoireFabricant:'Générique' },
    { nomCommercial:'Eau oxygénée 10 volumes', dci:'Peroxyde d\'hydrogène', classeTherapeutique:'Antiseptique cutané', forme:'Solution', dosage:'3%', laboratoireFabricant:'Générique' },
    { nomCommercial:'Bétaméthasone Crème 0,05%', dci:'Bétaméthasone valérate', classeTherapeutique:'Corticoïde topique dermique', forme:'Crème', dosage:'0,05%', laboratoireFabricant:'Générique' },
  ];

  let countMed = 0;
  for (const med of medicaments) {
    const exists = await prisma.medicament.findFirst({ where: { nomCommercial: med.nomCommercial } });
    if (!exists) { await prisma.medicament.create({ data: med }); countMed++; }
  }
  console.log(`✅ ${countMed} nouveaux médicaments ajoutés (${medicaments.length} dans la liste)`);

  // ══════════════════════════════════════════════════════════
  // EXAMENS
  // ══════════════════════════════════════════════════════════
  const examens = [
    { nom:'Numération Formule Sanguine (NFS)', codeAzamed:'HEM001', categorie:'Hématologie', description:'Globules rouges, blancs, plaquettes' },
    { nom:'Groupe Sanguin ABO + Rhésus', codeAzamed:'HEM002', categorie:'Hématologie', description:'Détermination groupe sanguin' },
    { nom:'Vitesse de Sédimentation (VS)', codeAzamed:'HEM003', categorie:'Hématologie', description:'Marqueur inflammatoire' },
    { nom:'Taux de Prothrombine (TP) / INR', codeAzamed:'HEM004', categorie:'Hématologie', description:'Coagulation - suivi AVK' },
    { nom:'Temps de Céphaline Activée (TCA)', codeAzamed:'HEM005', categorie:'Hématologie', description:'Exploration coagulation' },
    { nom:'Électrophorèse de l\'hémoglobine', codeAzamed:'HEM006', categorie:'Hématologie', description:'Dépistage drépanocytose' },
    { nom:'Frottis sanguin', codeAzamed:'HEM007', categorie:'Hématologie', description:'Morphologie cellules sanguines' },
    { nom:'Glycémie à jeun', codeAzamed:'BIO001', categorie:'Biochimie', description:'Dépistage diabète' },
    { nom:'Glycémie postprandiale 2h', codeAzamed:'BIO002', categorie:'Biochimie', description:'Diabète - glycémie après repas' },
    { nom:'HbA1c (Hémoglobine glyquée)', codeAzamed:'BIO003', categorie:'Biochimie', description:'Contrôle glycémique 3 mois' },
    { nom:'Créatininémie', codeAzamed:'BIO004', categorie:'Biochimie', description:'Fonction rénale' },
    { nom:'Urée sanguine', codeAzamed:'BIO005', categorie:'Biochimie', description:'Fonction rénale' },
    { nom:'Acide urique', codeAzamed:'BIO006', categorie:'Biochimie', description:'Goutte' },
    { nom:'Transaminases ALAT (SGPT)', codeAzamed:'BIO007', categorie:'Biochimie', description:'Bilan hépatique' },
    { nom:'Transaminases ASAT (SGOT)', codeAzamed:'BIO008', categorie:'Biochimie', description:'Bilan hépatique' },
    { nom:'Bilirubine totale + directe', codeAzamed:'BIO009', categorie:'Biochimie', description:'Ictère - bilan foie' },
    { nom:'Gamma GT (GGT)', codeAzamed:'BIO010', categorie:'Biochimie', description:'Marqueur hépatique' },
    { nom:'Protéines totales + Albumine', codeAzamed:'BIO011', categorie:'Biochimie', description:'Bilan nutritionnel et hépatique' },
    { nom:'Cholestérol total', codeAzamed:'BIO012', categorie:'Biochimie', description:'Bilan lipidique' },
    { nom:'HDL-Cholestérol', codeAzamed:'BIO013', categorie:'Biochimie', description:'Bon cholestérol' },
    { nom:'LDL-Cholestérol', codeAzamed:'BIO014', categorie:'Biochimie', description:'Mauvais cholestérol' },
    { nom:'Triglycérides', codeAzamed:'BIO015', categorie:'Biochimie', description:'Bilan lipidique' },
    { nom:'Ionogramme sanguin (Na, K, Cl)', codeAzamed:'BIO016', categorie:'Biochimie', description:'Électrolytes sanguins' },
    { nom:'Calcémie', codeAzamed:'BIO017', categorie:'Biochimie', description:'Calcium sanguin' },
    { nom:'CRP (Protéine C Réactive)', codeAzamed:'BIO018', categorie:'Biochimie', description:'Marqueur inflammatoire' },
    { nom:'Ferritine sérique', codeAzamed:'BIO019', categorie:'Biochimie', description:'Réserves en fer' },
    { nom:'TSH (Thyréostimuline)', codeAzamed:'BIO020', categorie:'Biochimie', description:'Bilan thyroïdien' },
    { nom:'T3 libre + T4 libre', codeAzamed:'BIO021', categorie:'Biochimie', description:'Hormones thyroïdiennes' },
    { nom:'Beta-HCG quantitatif', codeAzamed:'BIO022', categorie:'Biochimie', description:'Test grossesse + suivi GEU' },
    { nom:'Amylase + Lipase', codeAzamed:'BIO023', categorie:'Biochimie', description:'Bilan pancréatique' },
    { nom:'Troponine I ou T', codeAzamed:'BIO024', categorie:'Biochimie', description:'Infarctus du myocarde' },
    { nom:'PSA (Antigène Prostatique Spécifique)', codeAzamed:'BIO025', categorie:'Biochimie', description:'Dépistage cancer prostate' },
    { nom:'Procalcitonine (PCT)', codeAzamed:'BIO026', categorie:'Biochimie', description:'Marqueur sepsis bactérien' },
    { nom:'Test VIH (ELISA 4ème génération)', codeAzamed:'SER001', categorie:'Sérologie', description:'Dépistage VIH 1 et 2' },
    { nom:'Charge virale VIH', codeAzamed:'SER002', categorie:'Sérologie', description:'Suivi ARV - ARN VIH' },
    { nom:'CD4 (Lymphocytes T4)', codeAzamed:'SER003', categorie:'Sérologie', description:'Immunité VIH' },
    { nom:'Antigène HBs (Hépatite B)', codeAzamed:'SER004', categorie:'Sérologie', description:'Dépistage hépatite B' },
    { nom:'Anticorps anti-HBs', codeAzamed:'SER005', categorie:'Sérologie', description:'Immunité post-vaccinale HBV' },
    { nom:'Charge virale VHB', codeAzamed:'SER006', categorie:'Sérologie', description:'ADN hépatite B' },
    { nom:'Anticorps anti-VHC', codeAzamed:'SER007', categorie:'Sérologie', description:'Dépistage hépatite C' },
    { nom:'Charge virale VHC', codeAzamed:'SER008', categorie:'Sérologie', description:'ARN hépatite C' },
    { nom:'VDRL + TPHA (Syphilis)', codeAzamed:'SER009', categorie:'Sérologie', description:'Dépistage syphilis' },
    { nom:'Sérologie Toxoplasmose IgG + IgM', codeAzamed:'SER010', categorie:'Sérologie', description:'Toxoplasmose - grossesse' },
    { nom:'Sérologie Rubéole IgG + IgM', codeAzamed:'SER011', categorie:'Sérologie', description:'Immunité rubéole - grossesse' },
    { nom:'Sérologie Typhoïde (Widal-Félix)', codeAzamed:'SER012', categorie:'Sérologie', description:'Fièvre typhoïde' },
    { nom:'Facteur Rhumatoïde (FR)', codeAzamed:'SER013', categorie:'Sérologie', description:'Polyarthrite rhumatoïde' },
    { nom:'Goutte épaisse + Frottis (Paludisme)', codeAzamed:'PAR001', categorie:'Parasitologie', description:'Diagnostic de référence paludisme' },
    { nom:'TDR Paludisme (Test Rapide)', codeAzamed:'PAR002', categorie:'Parasitologie', description:'Résultat rapide paludisme' },
    { nom:'PCR Paludisme', codeAzamed:'PAR003', categorie:'Parasitologie', description:'Diagnostic moléculaire paludisme' },
    { nom:'Examen Parasitologique Selles (EPS)', codeAzamed:'PAR004', categorie:'Parasitologie', description:'Parasites intestinaux' },
    { nom:'Recherche Filaires (Loase, Onchocercose)', codeAzamed:'PAR005', categorie:'Parasitologie', description:'Microfilarémie' },
    { nom:'Examen Parasitologique Urine (Bilharziose)', codeAzamed:'PAR006', categorie:'Parasitologie', description:'Schistosoma haematobium' },
    { nom:'ECBU (Examen Cytobactério Urinaire)', codeAzamed:'BAC001', categorie:'Bactériologie', description:'Infection urinaire + antibiogramme' },
    { nom:'Hémoculture', codeAzamed:'BAC002', categorie:'Bactériologie', description:'Septicémie - bactéries dans le sang' },
    { nom:'Coproculture', codeAzamed:'BAC003', categorie:'Bactériologie', description:'Germes pathogènes selles' },
    { nom:'Examen Bactério Sécrétions Vaginales', codeAzamed:'BAC004', categorie:'Bactériologie', description:'Vaginite + antibiogramme' },
    { nom:'Examen Bactério Expectorations (BAAR)', codeAzamed:'BAC005', categorie:'Bactériologie', description:'Bacilles Acido-Alcoolo-Résistants - TB' },
    { nom:'GeneXpert MTB/RIF (Tuberculose)', codeAzamed:'BAC006', categorie:'Bactériologie', description:'Diagnostic rapide TB + résistance Rifampicine' },
    { nom:'Antibiogramme', codeAzamed:'BAC007', categorie:'Bactériologie', description:'Sensibilité aux antibiotiques' },
    { nom:'Radiographie thoracique Face', codeAzamed:'IMG001', categorie:'Imagerie', description:'Poumons, coeur, médiastin' },
    { nom:'Radiographie abdomen sans préparation', codeAzamed:'IMG002', categorie:'Imagerie', description:'Occlusion, calcifications' },
    { nom:'Radiographie bassin / membres', codeAzamed:'IMG003', categorie:'Imagerie', description:'Fractures, arthrose' },
    { nom:'Radiographie rachis cervical / lombaire', codeAzamed:'IMG004', categorie:'Imagerie', description:'Lombalgies, hernie discale' },
    { nom:'Échographie abdominale + pelvienne', codeAzamed:'IMG005', categorie:'Imagerie', description:'Foie, vésicule, reins, organes pelviens' },
    { nom:'Échographie obstétricale (Grossesse)', codeAzamed:'IMG006', categorie:'Imagerie', description:'Surveillance grossesse - datation, biométrie' },
    { nom:'Échographie thyroïde', codeAzamed:'IMG007', categorie:'Imagerie', description:'Nodules, goitre' },
    { nom:'Échographie cardiaque (Échocardiographie)', codeAzamed:'IMG008', categorie:'Imagerie', description:'Fonction cardiaque' },
    { nom:'Électrocardiogramme (ECG)', codeAzamed:'IMG009', categorie:'Imagerie', description:'Activité électrique cardiaque' },
    { nom:'Scanner thoracique (TDM)', codeAzamed:'IMG010', categorie:'Imagerie', description:'Tuberculose, masses pulmonaires' },
    { nom:'Scanner cérébral (TDM)', codeAzamed:'IMG011', categorie:'Imagerie', description:'AVC, traumatisme crânien, tumeurs' },
    { nom:'Scanner abdomino-pelvien (TDM)', codeAzamed:'IMG012', categorie:'Imagerie', description:'Tumeurs, urgences abdominales' },
    { nom:'IRM cérébrale', codeAzamed:'IMG013', categorie:'Imagerie', description:'Épilepsie, SEP, AVC' },
    { nom:'IRM rachidienne', codeAzamed:'IMG014', categorie:'Imagerie', description:'Hernie discale, compression médullaire' },
    { nom:'Mammographie', codeAzamed:'IMG015', categorie:'Imagerie', description:'Dépistage cancer du sein' },
    { nom:'Frottis cervico-vaginal (FCV / Pap test)', codeAzamed:'ANA001', categorie:'Anatomopathologie', description:'Dépistage cancer col utérus' },
    { nom:'Biopsie hépatique', codeAzamed:'ANA002', categorie:'Anatomopathologie', description:'Fibrose - hépatite chronique' },
    { nom:'Biopsie ganglionnaire', codeAzamed:'ANA003', categorie:'Anatomopathologie', description:'Lymphome, tuberculose ganglionnaire' },
    { nom:'Examen anatomopathologique (pièce opératoire)', codeAzamed:'ANA004', categorie:'Anatomopathologie', description:'Histologie pièces chirurgicales' },
    { nom:'Spermiogramme', codeAzamed:'URO001', categorie:'Urologie', description:'Infertilité masculine' },
    { nom:'Microalbuminurie', codeAzamed:'URO002', categorie:'Urologie', description:'Néphropathie débutante - diabète, HTA' },
    { nom:'Créatinine + Protéinurie des 24h', codeAzamed:'URO003', categorie:'Urologie', description:'Clairance rénale - protéinurie' },
  ];

  let countEx = 0;
  for (const ex of examens) {
    const exists = await prisma.examen.findUnique({ where: { codeAzamed: ex.codeAzamed } });
    if (!exists) { await prisma.examen.create({ data: ex }); countEx++; }
  }
  console.log(`✅ ${countEx} nouveaux examens ajoutés (${examens.length} dans la liste)`);

  // ══════════════════════════════════════════════════════════
  // SERVICES MÉDICAUX
  // ══════════════════════════════════════════════════════════
  const services = [
    { nom:'Médecine Générale', categorie:'Spécialité médicale', description:'Consultations de médecine générale' },
    { nom:'Pédiatrie', categorie:'Spécialité médicale', description:'Médecine des enfants 0-15 ans' },
    { nom:'Cardiologie', categorie:'Spécialité médicale', description:'Maladies du coeur et vaisseaux' },
    { nom:'Pneumologie', categorie:'Spécialité médicale', description:'Maladies poumons et voies respiratoires' },
    { nom:'Neurologie', categorie:'Spécialité médicale', description:'Maladies du système nerveux' },
    { nom:'Gastro-Entérologie', categorie:'Spécialité médicale', description:'Maladies tube digestif et foie' },
    { nom:'Endocrinologie - Diabétologie', categorie:'Spécialité médicale', description:'Diabète, thyroïde, hormones' },
    { nom:'Infectiologie', categorie:'Spécialité médicale', description:'VIH, tuberculose, paludisme sévère, IST' },
    { nom:'Rhumatologie', categorie:'Spécialité médicale', description:'Articulations et os' },
    { nom:'Hématologie', categorie:'Spécialité médicale', description:'Anémie, drépanocytose, leucémie' },
    { nom:'Oncologie - Cancérologie', categorie:'Spécialité médicale', description:'Prévention, diagnostic et traitement cancers' },
    { nom:'Dermatologie', categorie:'Spécialité médicale', description:'Maladies peau, cheveux, ongles' },
    { nom:'ORL (Oto-Rhino-Laryngologie)', categorie:'Spécialité médicale', description:'Oreille, nez, gorge' },
    { nom:'Ophtalmologie', categorie:'Spécialité médicale', description:'Maladies des yeux - vue, glaucome, cataracte' },
    { nom:'Stomatologie - Odontologie', categorie:'Spécialité médicale', description:'Soins dentaires et bucco-dentaires' },
    { nom:'Psychiatrie - Santé mentale', categorie:'Spécialité médicale', description:'Maladies mentales, dépression, addictions' },
    { nom:'Néphrologie', categorie:'Spécialité médicale', description:'Maladies des reins, dialyse' },
    { nom:'Urologie', categorie:'Spécialité médicale', description:'Voies urinaires et génital masculin' },
    { nom:'Médecine Interne', categorie:'Spécialité médicale', description:'Maladies systémiques complexes' },
    { nom:'Gériatrie', categorie:'Spécialité médicale', description:'Médecine des personnes âgées' },
    { nom:'Chirurgie Générale', categorie:'Spécialité chirurgicale', description:'Chirurgie digestive, abdominale, hernies' },
    { nom:'Chirurgie Orthopédique et Traumatologique', categorie:'Spécialité chirurgicale', description:'Os, articulations, fractures, prothèses' },
    { nom:'Neurochirurgie', categorie:'Spécialité chirurgicale', description:'Chirurgie cerveau et moelle épinière' },
    { nom:'Chirurgie Cardio-Vasculaire', categorie:'Spécialité chirurgicale', description:'Coeur et gros vaisseaux' },
    { nom:'Chirurgie Thoracique', categorie:'Spécialité chirurgicale', description:'Poumons, plèvre, médiastin' },
    { nom:'Chirurgie Urologique', categorie:'Spécialité chirurgicale', description:'Rein, prostate, urètre' },
    { nom:'Chirurgie Pédiatrique', categorie:'Spécialité chirurgicale', description:'Chirurgie chez l\'enfant' },
    { nom:'Chirurgie Plastique et Reconstructrice', categorie:'Spécialité chirurgicale', description:'Cicatrices, brûlures, reconstructions' },
    { nom:'Chirurgie Ophtalmologique', categorie:'Spécialité chirurgicale', description:'Cataracte, glaucome, décollement rétine' },
    { nom:'Chirurgie ORL', categorie:'Spécialité chirurgicale', description:'Amygdales, végétations, sinus' },
    { nom:'Chirurgie Stomatologique', categorie:'Spécialité chirurgicale', description:'Extractions, chirurgie maxillo-faciale' },
    { nom:'Gynécologie Médicale', categorie:'Gynécologie-Obstétrique', description:'Consultations gynécologiques, contraception, IST' },
    { nom:'Obstétrique - Suivi de Grossesse', categorie:'Gynécologie-Obstétrique', description:'Consultations prénatales, échographies' },
    { nom:'Accouchement Normal (Voie Basse)', categorie:'Gynécologie-Obstétrique', description:'Accouchement par voie naturelle' },
    { nom:'Accouchement par Césarienne', categorie:'Gynécologie-Obstétrique', description:'Accouchement chirurgical' },
    { nom:'Planning Familial', categorie:'Gynécologie-Obstétrique', description:'Contraception, counseling, DIU, implants' },
    { nom:'Consultation Post-natale', categorie:'Gynécologie-Obstétrique', description:'Suivi mère et nourrisson après accouchement' },
    { nom:'Dépistage Cancer du Col (FCV)', categorie:'Gynécologie-Obstétrique', description:'Frottis cervico-vaginal, colposcopie' },
    { nom:'Urgences Médicales et Chirurgicales 24h/24', categorie:'Urgences', description:'Prise en charge urgences toutes pathologies' },
    { nom:'Réanimation Adulte', categorie:'Urgences', description:'Soins intensifs adultes' },
    { nom:'Réanimation Pédiatrique / Néonatale', categorie:'Urgences', description:'Soins intensifs enfants et nouveau-nés' },
    { nom:'SMUR / Ambulance médicalisée', categorie:'Urgences', description:'Urgences pré-hospitalières et transport médicalisé' },
    { nom:'Hospitalisation Médecine Adulte', categorie:'Hospitalisation', description:'Chambres d\'hospitalisation médecine' },
    { nom:'Hospitalisation Chirurgie', categorie:'Hospitalisation', description:'Chambres post-opératoires' },
    { nom:'Hospitalisation Pédiatrique', categorie:'Hospitalisation', description:'Chambres enfants' },
    { nom:'Hospitalisation Maternité', categorie:'Hospitalisation', description:'Chambres mère-enfant' },
    { nom:'Laboratoire d\'Analyses Médicales Interne', categorie:'Plateau technique', description:'Analyses biologiques sur place' },
    { nom:'Pharmacie Hospitalière Interne', categorie:'Plateau technique', description:'Dispensation médicaments intra-hospitaliers' },
    { nom:'Bloc Opératoire', categorie:'Plateau technique', description:'Salle d\'opération chirurgicale' },
    { nom:'Radiologie et Imagerie Médicale', categorie:'Plateau technique', description:'Radio, échographie, scanner, IRM' },
    { nom:'Endoscopie Digestive (Fibroscopie/Coloscopie)', categorie:'Plateau technique', description:'Gastroscopie, coloscopie' },
    { nom:'Hémodialyse (Dialyse rénale)', categorie:'Plateau technique', description:'Épuration extrarénale - insuffisance rénale' },
    { nom:'Transfusion sanguine (Banque de sang)', categorie:'Plateau technique', description:'Collecte, analyse et dispensation sang' },
    { nom:'Kinésithérapie - Rééducation', categorie:'Plateau technique', description:'Rééducation motrice, respiratoire, neurologique' },
    { nom:'Consultation Nutritionnelle - Diététique', categorie:'Plateau technique', description:'Obésité, dénutrition, régimes thérapeutiques' },
    { nom:'Vaccination Enfant (PEV)', categorie:'Prévention', description:'Programme Élargi Vaccination - BCG, Polio, Rougeole...' },
    { nom:'Vaccination Adulte', categorie:'Prévention', description:'Tétanos, fièvre jaune, méningite, hépatite B...' },
    { nom:'Consultation Prénatale (CPN)', categorie:'Prévention', description:'Suivi médical femmes enceintes' },
    { nom:'PTME (Prévention Transmission Mère-Enfant VIH)', categorie:'Prévention', description:'Dépistage VIH et ARV en maternité' },
    { nom:'Dépistage VIH / Conseil Dépistage', categorie:'Prévention', description:'Test VIH + counseling pré et post test' },
    { nom:'TPI Paludisme (Sulfadoxine-Pyriméthamine)', categorie:'Prévention', description:'Traitement Préventif Intermittent paludisme grossesse' },
    { nom:'Déparasitage - Vermifugation', categorie:'Prévention', description:'Albendazole, mébendazole - enfants' },
    { nom:'Distribution Moustiquaires Imprégnées (MILDA)', categorie:'Prévention', description:'Prévention paludisme' },
    { nom:'Médecine du Travail', categorie:'Prévention', description:'Visites médicales professionnelles, aptitude' },
    { nom:'Centre de Traitement ARV (VIH)', categorie:'Spécialités Cameroun', description:'Initiation et suivi traitement antirétroviral' },
    { nom:'Centre de Traitement Tuberculose (CDT)', categorie:'Spécialités Cameroun', description:'Diagnostic et traitement DOTS tuberculose' },
    { nom:'Prise en charge Drépanocytose', categorie:'Spécialités Cameroun', description:'Suivi et traitement patients drépanocytaires' },
    { nom:'Unité Nutritionnelle Thérapeutique (UNTA/UNTI)', categorie:'Spécialités Cameroun', description:'Prise en charge malnutrition aiguë sévère' },
    { nom:'Soins Palliatifs', categorie:'Spécialités Cameroun', description:'Accompagnement fin de vie - cancer, SIDA' },
    { nom:'Prise en charge Hypertension Artérielle (HTA)', categorie:'Spécialités Cameroun', description:'Consultation spécialisée HTA' },
    { nom:'Consultation Diabète', categorie:'Spécialités Cameroun', description:'Suivi spécialisé diabète type 1 et 2' },
    { nom:'Opération Cataracte', categorie:'Spécialités Cameroun', description:'Chirurgie cataracte - cécité évitable' },
    { nom:'Programme Santé Mentale Communautaire', categorie:'Spécialités Cameroun', description:'Prise en charge psychiatrique ambulatoire' },
    { nom:'Vente Médicaments sur Ordonnance', categorie:'Services Pharmacie', description:'Dispensation médicaments prescrits' },
    { nom:'Vente Médicaments sans Ordonnance (OTC)', categorie:'Services Pharmacie', description:'Médicaments disponibles sans prescription' },
    { nom:'Pharmacie de Garde (Nuit / Weekend)', categorie:'Services Pharmacie', description:'Disponible nuits, weekends et jours fériés' },
    { nom:'Conseil Pharmaceutique', categorie:'Services Pharmacie', description:'Orientation et information sur les médicaments' },
    { nom:'Vente Matériel Médical Paramédical', categorie:'Services Pharmacie', description:'Seringues, pansements, tensiomètres, glucomètres...' },
    { nom:'Produits de Parapharmacie', categorie:'Services Pharmacie', description:'Cosmétiques, compléments alimentaires, bébé' },
    { nom:'Analyses en Urgence (H24)', categorie:'Services Laboratoire', description:'Résultats urgents disponibles nuit et jour' },
    { nom:'Prélèvement à Domicile', categorie:'Services Laboratoire', description:'Technicien qui se déplace au domicile' },
    { nom:'Bilan Prénuptial', categorie:'Services Laboratoire', description:'VIH, syphilis, groupe sanguin avant mariage' },
    { nom:'Bilan Prénatal Complet', categorie:'Services Laboratoire', description:'NFS, groupe, VIH, syphilis, toxo, glycémie' },
    { nom:'Bilan Préopératoire', categorie:'Services Laboratoire', description:'NFS, coagulation, groupe, ionogramme avant chirurgie' },
    { nom:'Bilan Annuel de Santé', categorie:'Services Laboratoire', description:'Bilan routine - glycémie, lipides, rein, foie, NFS' },
  ];

  let countSvc = 0;
  for (const svc of services) {
    const exists = await prisma.serviceMedical.findFirst({ where: { nom: svc.nom } });
    if (!exists) { await prisma.serviceMedical.create({ data: svc }); countSvc++; }
  }
  console.log(`✅ ${countSvc} nouveaux services ajoutés (${services.length} dans la liste)`);

  console.log('\n🎉 Seed Cameroun terminé !');
  console.log(`📊 ${medicaments.length} médicaments | ${examens.length} examens | ${services.length} services`);
}

main()
  .catch((e) => { console.error('❌ Erreur:', e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
