// src/prisma/seed-data.js — Données catalogue Cameroun
// Ce fichier est utilisé par la route POST /api/admin/seed-catalogue

const MEDICAMENTS = [
  // ── Antibiotiques ──────────────────────────────────────────
  { nomCommercial:'Amoxicilline 500mg', dci:'Amoxicilline', classeTherapeutique:'Antibiotique', forme:'Gélule', dosage:'500mg', laboratoireFabricant:'Beaufour Ipsen' },
  { nomCommercial:'Augmentin 1g', dci:'Amoxicilline/Acide clavulanique', classeTherapeutique:'Antibiotique', forme:'Comprimé', dosage:'1g', laboratoireFabricant:'GSK' },
  { nomCommercial:'Ciprofloxacine 500mg', dci:'Ciprofloxacine', classeTherapeutique:'Antibiotique', forme:'Comprimé', dosage:'500mg', laboratoireFabricant:'Bayer' },
  { nomCommercial:'Metronidazole 500mg', dci:'Metronidazole', classeTherapeutique:'Antibiotique', forme:'Comprimé', dosage:'500mg', laboratoireFabricant:'Sanofi' },
  { nomCommercial:'Doxycycline 100mg', dci:'Doxycycline', classeTherapeutique:'Antibiotique', forme:'Gélule', dosage:'100mg', laboratoireFabricant:'Pfizer' },
  { nomCommercial:'Azithromycine 500mg', dci:'Azithromycine', classeTherapeutique:'Antibiotique', forme:'Comprimé', dosage:'500mg', laboratoireFabricant:'Pfizer' },
  { nomCommercial:'Ceftriaxone 1g', dci:'Ceftriaxone', classeTherapeutique:'Antibiotique', forme:'Injectable', dosage:'1g', laboratoireFabricant:'Roche' },
  { nomCommercial:'Cotrimoxazole 480mg', dci:'Sulfamethoxazole/Trimethoprime', classeTherapeutique:'Antibiotique', forme:'Comprimé', dosage:'480mg', laboratoireFabricant:'Cipla' },
  { nomCommercial:'Ampicilline 500mg', dci:'Ampicilline', classeTherapeutique:'Antibiotique', forme:'Gélule', dosage:'500mg', laboratoireFabricant:'Beaufour Ipsen' },
  { nomCommercial:'Gentamicine 80mg', dci:'Gentamicine', classeTherapeutique:'Antibiotique', forme:'Injectable', dosage:'80mg', laboratoireFabricant:'Sanofi' },
  { nomCommercial:'Ofloxacine 200mg', dci:'Ofloxacine', classeTherapeutique:'Antibiotique', forme:'Comprimé', dosage:'200mg', laboratoireFabricant:'Sanofi' },
  { nomCommercial:'Clindamycine 300mg', dci:'Clindamycine', classeTherapeutique:'Antibiotique', forme:'Gélule', dosage:'300mg', laboratoireFabricant:'Pfizer' },
  { nomCommercial:'Norfloxacine 400mg', dci:'Norfloxacine', classeTherapeutique:'Antibiotique', forme:'Comprimé', dosage:'400mg', laboratoireFabricant:'Merck' },
  { nomCommercial:'Nitrofurantoine 100mg', dci:'Nitrofurantoine', classeTherapeutique:'Antibiotique', forme:'Gélule', dosage:'100mg', laboratoireFabricant:'Sanofi' },
  { nomCommercial:'Amoxicilline suspension 250mg/5mL', dci:'Amoxicilline', classeTherapeutique:'Antibiotique', forme:'Suspension', dosage:'250mg/5mL', laboratoireFabricant:'Beaufour' },
  { nomCommercial:'Cotrimoxazole suspension 240mg/5mL', dci:'Sulfamethoxazole/Trimethoprime', classeTherapeutique:'Antibiotique', forme:'Suspension', dosage:'240mg/5mL', laboratoireFabricant:'Cipla' },
  // ── Antipaludéens ──────────────────────────────────────────
  { nomCommercial:'Coartem', dci:'Artemether/Lumefantrine', classeTherapeutique:'Antipaludéen', forme:'Comprimé', dosage:'20/120mg', laboratoireFabricant:'Novartis' },
  { nomCommercial:'Quinine injectable 500mg', dci:'Quinine', classeTherapeutique:'Antipaludéen', forme:'Injectable', dosage:'500mg', laboratoireFabricant:'Sanofi' },
  { nomCommercial:'Chloroquine 250mg', dci:'Chloroquine', classeTherapeutique:'Antipaludéen', forme:'Comprimé', dosage:'250mg', laboratoireFabricant:'Sanofi' },
  { nomCommercial:'Artesunate 200mg', dci:'Artesunate', classeTherapeutique:'Antipaludéen', forme:'Comprimé', dosage:'200mg', laboratoireFabricant:'Dafra Pharma' },
  { nomCommercial:'Artesunate injectable 60mg', dci:'Artesunate', classeTherapeutique:'Antipaludéen', forme:'Injectable', dosage:'60mg', laboratoireFabricant:'Guilin' },
  { nomCommercial:'Fansidar', dci:'Sulfadoxine/Pyrimethamine', classeTherapeutique:'Antipaludéen', forme:'Comprimé', dosage:'500/25mg', laboratoireFabricant:'Roche' },
  { nomCommercial:'Pyramax', dci:'Pyronaridine/Artesunate', classeTherapeutique:'Antipaludéen', forme:'Comprimé', dosage:'180/60mg', laboratoireFabricant:'Shin Poong' },
  { nomCommercial:'Mefloquine 250mg', dci:'Mefloquine', classeTherapeutique:'Antipaludéen', forme:'Comprimé', dosage:'250mg', laboratoireFabricant:'Roche' },
  // ── Antalgiques/Anti-inflammatoires ────────────────────────
  { nomCommercial:'Paracetamol 500mg', dci:'Paracetamol', classeTherapeutique:'Antalgique/Antipyrétique', forme:'Comprimé', dosage:'500mg', laboratoireFabricant:'Sanofi' },
  { nomCommercial:'Paracetamol 1g', dci:'Paracetamol', classeTherapeutique:'Antalgique/Antipyrétique', forme:'Comprimé', dosage:'1g', laboratoireFabricant:'UPSA' },
  { nomCommercial:'Paracetamol sirop 150mg/5mL', dci:'Paracetamol', classeTherapeutique:'Antalgique/Antipyrétique', forme:'Sirop', dosage:'150mg/5mL', laboratoireFabricant:'UPSA' },
  { nomCommercial:'Ibuprofene 400mg', dci:'Ibuprofene', classeTherapeutique:'Anti-inflammatoire AINS', forme:'Comprimé', dosage:'400mg', laboratoireFabricant:'Sanofi' },
  { nomCommercial:'Diclofenac 75mg injectable', dci:'Diclofenac', classeTherapeutique:'Anti-inflammatoire AINS', forme:'Injectable', dosage:'75mg', laboratoireFabricant:'Novartis' },
  { nomCommercial:'Voltarene 50mg', dci:'Diclofenac sodique', classeTherapeutique:'Anti-inflammatoire AINS', forme:'Comprimé', dosage:'50mg', laboratoireFabricant:'Novartis' },
  { nomCommercial:'Ketoprofene 100mg', dci:'Ketoprofene', classeTherapeutique:'Anti-inflammatoire AINS', forme:'Gélule', dosage:'100mg', laboratoireFabricant:'Sanofi' },
  { nomCommercial:'Tramadol 100mg injectable', dci:'Tramadol', classeTherapeutique:'Antalgique opioïde', forme:'Injectable', dosage:'100mg', laboratoireFabricant:'Grunenthal' },
  { nomCommercial:'Prednisolone 5mg', dci:'Prednisolone', classeTherapeutique:'Corticoïde', forme:'Comprimé', dosage:'5mg', laboratoireFabricant:'Sanofi' },
  { nomCommercial:'Dexamethasone 4mg injectable', dci:'Dexamethasone', classeTherapeutique:'Corticoïde', forme:'Injectable', dosage:'4mg', laboratoireFabricant:'Merck' },
  { nomCommercial:'Dexamethasone 8mg injectable', dci:'Dexamethasone', classeTherapeutique:'Corticoïde', forme:'Injectable', dosage:'8mg', laboratoireFabricant:'Merck' },
  // ── Antidiabétiques ────────────────────────────────────────
  { nomCommercial:'Metformine 500mg', dci:'Metformine', classeTherapeutique:'Antidiabétique', forme:'Comprimé', dosage:'500mg', laboratoireFabricant:'Merck' },
  { nomCommercial:'Metformine 1000mg', dci:'Metformine', classeTherapeutique:'Antidiabétique', forme:'Comprimé', dosage:'1000mg', laboratoireFabricant:'Merck' },
  { nomCommercial:'Glibenclamide 5mg', dci:'Glibenclamide', classeTherapeutique:'Antidiabétique', forme:'Comprimé', dosage:'5mg', laboratoireFabricant:'Sanofi' },
  { nomCommercial:'Glicazide 80mg', dci:'Glicazide', classeTherapeutique:'Antidiabétique', forme:'Comprimé', dosage:'80mg', laboratoireFabricant:'Servier' },
  { nomCommercial:'Insuline Rapide 100UI', dci:'Insuline humaine', classeTherapeutique:'Antidiabétique', forme:'Injectable', dosage:'100UI/mL', laboratoireFabricant:'Novo Nordisk' },
  { nomCommercial:'Insuline NPH 100UI', dci:'Insuline isophane', classeTherapeutique:'Antidiabétique', forme:'Injectable', dosage:'100UI/mL', laboratoireFabricant:'Novo Nordisk' },
  // ── Antihypertenseurs ──────────────────────────────────────
  { nomCommercial:'Amlodipine 5mg', dci:'Amlodipine', classeTherapeutique:'Antihypertenseur', forme:'Comprimé', dosage:'5mg', laboratoireFabricant:'Pfizer' },
  { nomCommercial:'Amlodipine 10mg', dci:'Amlodipine', classeTherapeutique:'Antihypertenseur', forme:'Comprimé', dosage:'10mg', laboratoireFabricant:'Pfizer' },
  { nomCommercial:'Captopril 25mg', dci:'Captopril', classeTherapeutique:'Antihypertenseur IEC', forme:'Comprimé', dosage:'25mg', laboratoireFabricant:'BMS' },
  { nomCommercial:'Enalapril 10mg', dci:'Enalapril', classeTherapeutique:'Antihypertenseur IEC', forme:'Comprimé', dosage:'10mg', laboratoireFabricant:'Merck' },
  { nomCommercial:'Losartan 50mg', dci:'Losartan', classeTherapeutique:'Antihypertenseur ARA2', forme:'Comprimé', dosage:'50mg', laboratoireFabricant:'MSD' },
  { nomCommercial:'Furosemide 40mg', dci:'Furosemide', classeTherapeutique:'Diurétique', forme:'Comprimé', dosage:'40mg', laboratoireFabricant:'Sanofi' },
  { nomCommercial:'Hydrochlorothiazide 25mg', dci:'Hydrochlorothiazide', classeTherapeutique:'Diurétique', forme:'Comprimé', dosage:'25mg', laboratoireFabricant:'Novartis' },
  { nomCommercial:'Atenolol 50mg', dci:'Atenolol', classeTherapeutique:'Bêtabloquant', forme:'Comprimé', dosage:'50mg', laboratoireFabricant:'AstraZeneca' },
  { nomCommercial:'Propranolol 40mg', dci:'Propranolol', classeTherapeutique:'Bêtabloquant', forme:'Comprimé', dosage:'40mg', laboratoireFabricant:'AstraZeneca' },
  { nomCommercial:'Methyldopa 250mg', dci:'Methyldopa', classeTherapeutique:'Antihypertenseur central', forme:'Comprimé', dosage:'250mg', laboratoireFabricant:'Merck' },
  // ── Gastro ────────────────────────────────────────────────
  { nomCommercial:'Omeprazole 20mg', dci:'Omeprazole', classeTherapeutique:'Antiulcéreux IPP', forme:'Gélule', dosage:'20mg', laboratoireFabricant:'AstraZeneca' },
  { nomCommercial:'Omeprazole 40mg injectable', dci:'Omeprazole', classeTherapeutique:'Antiulcéreux IPP', forme:'Injectable', dosage:'40mg', laboratoireFabricant:'AstraZeneca' },
  { nomCommercial:'Pantoprazole 40mg', dci:'Pantoprazole', classeTherapeutique:'Antiulcéreux IPP', forme:'Comprimé', dosage:'40mg', laboratoireFabricant:'Nycomed' },
  { nomCommercial:'Metoclopramide 10mg', dci:'Metoclopramide', classeTherapeutique:'Antiémétique', forme:'Comprimé', dosage:'10mg', laboratoireFabricant:'Sanofi' },
  { nomCommercial:'Loperamide 2mg', dci:'Loperamide', classeTherapeutique:'Antidiarrhéique', forme:'Gélule', dosage:'2mg', laboratoireFabricant:'J&J' },
  { nomCommercial:'Spasfon 80mg', dci:'Phloroglucinol', classeTherapeutique:'Antispasmodique', forme:'Comprimé', dosage:'80mg', laboratoireFabricant:'Lafon' },
  { nomCommercial:'Maalox suspension', dci:'Aluminium/Magnesium hydroxyde', classeTherapeutique:'Antiacide', forme:'Suspension', dosage:'4%/3.5%', laboratoireFabricant:'Sanofi' },
  { nomCommercial:'SRO sachet standard', dci:'Sels de rehydratation orale', classeTherapeutique:'Réhydratation', forme:'Poudre', dosage:'1 sachet/200mL', laboratoireFabricant:'OMS/UNICEF' },
  // ── Vitamines/Mineraux ─────────────────────────────────────
  { nomCommercial:'Vitamine C 500mg', dci:'Acide ascorbique', classeTherapeutique:'Vitamine', forme:'Comprimé effervescent', dosage:'500mg', laboratoireFabricant:'Bayer' },
  { nomCommercial:'Vitamine B complexe', dci:'Vitamines B1/B6/B12', classeTherapeutique:'Vitamine', forme:'Comprimé', dosage:'100mg', laboratoireFabricant:'Sanofi' },
  { nomCommercial:'Vitamine D3 800UI', dci:'Cholecalciferol', classeTherapeutique:'Vitamine', forme:'Comprimé', dosage:'800UI', laboratoireFabricant:'Merck' },
  { nomCommercial:'Fer sulfate 200mg', dci:'Sulfate ferreux', classeTherapeutique:'Antianémique', forme:'Comprimé', dosage:'200mg', laboratoireFabricant:'Sanofi' },
  { nomCommercial:'Fer sirop 50mg/5mL', dci:'Sulfate ferreux', classeTherapeutique:'Antianémique', forme:'Sirop', dosage:'50mg/5mL', laboratoireFabricant:'Sanofi' },
  { nomCommercial:'Acide folique 5mg', dci:'Acide folique', classeTherapeutique:'Vitamine B9', forme:'Comprimé', dosage:'5mg', laboratoireFabricant:'Sanofi' },
  { nomCommercial:'Calcium 500mg', dci:'Carbonate de calcium', classeTherapeutique:'Minéral', forme:'Comprimé', dosage:'500mg', laboratoireFabricant:'Bayer' },
  { nomCommercial:'Zinc 20mg', dci:'Gluconate de zinc', classeTherapeutique:'Minéral', forme:'Comprimé', dosage:'20mg', laboratoireFabricant:'Sanofi' },
  { nomCommercial:'Zinc sirop 10mg/5mL', dci:'Gluconate de zinc', classeTherapeutique:'Minéral', forme:'Sirop', dosage:'10mg/5mL', laboratoireFabricant:'Sanofi' },
  // ── Antiparasitaires ───────────────────────────────────────
  { nomCommercial:'Albendazole 400mg', dci:'Albendazole', classeTherapeutique:'Antiparasitaire', forme:'Comprimé', dosage:'400mg', laboratoireFabricant:'GSK' },
  { nomCommercial:'Ivermectine 6mg', dci:'Ivermectine', classeTherapeutique:'Antiparasitaire', forme:'Comprimé', dosage:'6mg', laboratoireFabricant:'MSD' },
  { nomCommercial:'Praziquantel 600mg', dci:'Praziquantel', classeTherapeutique:'Antiparasitaire', forme:'Comprimé', dosage:'600mg', laboratoireFabricant:'Bayer' },
  { nomCommercial:'Mebendazole 500mg', dci:'Mebendazole', classeTherapeutique:'Antiparasitaire', forme:'Comprimé', dosage:'500mg', laboratoireFabricant:'J&J' },
  { nomCommercial:'Tinidazole 500mg', dci:'Tinidazole', classeTherapeutique:'Antiparasitaire', forme:'Comprimé', dosage:'500mg', laboratoireFabricant:'Pfizer' },
  // ── Antifongiques ──────────────────────────────────────────
  { nomCommercial:'Fluconazole 150mg', dci:'Fluconazole', classeTherapeutique:'Antifongique', forme:'Gélule', dosage:'150mg', laboratoireFabricant:'Pfizer' },
  { nomCommercial:'Ketoconazole 200mg', dci:'Ketoconazole', classeTherapeutique:'Antifongique', forme:'Comprimé', dosage:'200mg', laboratoireFabricant:'J&J' },
  { nomCommercial:'Nystatine 500000UI', dci:'Nystatine', classeTherapeutique:'Antifongique', forme:'Comprimé', dosage:'500000UI', laboratoireFabricant:'Squibb' },
  { nomCommercial:'Clotrimazole creme 1%', dci:'Clotrimazole', classeTherapeutique:'Antifongique topique', forme:'Crème', dosage:'1%', laboratoireFabricant:'Bayer' },
  // ── ARV/VIH ────────────────────────────────────────────────
  { nomCommercial:'ARV TDF/3TC/EFV', dci:'Tenofovir/Lamivudine/Efavirenz', classeTherapeutique:'Antirétroviral', forme:'Comprimé', dosage:'300/300/600mg', laboratoireFabricant:'Cipla' },
  { nomCommercial:'Zidovudine 300mg', dci:'Zidovudine', classeTherapeutique:'Antirétroviral', forme:'Comprimé', dosage:'300mg', laboratoireFabricant:'GSK' },
  { nomCommercial:'Nevirapine 200mg', dci:'Nevirapine', classeTherapeutique:'Antirétroviral', forme:'Comprimé', dosage:'200mg', laboratoireFabricant:'Boehringer' },
  { nomCommercial:'Aciclovir 200mg', dci:'Aciclovir', classeTherapeutique:'Antiviral', forme:'Comprimé', dosage:'200mg', laboratoireFabricant:'GSK' },
  // ── Cardio ────────────────────────────────────────────────
  { nomCommercial:'Aspirine 100mg', dci:'Acide acetylsalicylique', classeTherapeutique:'Antiagrégant plaquettaire', forme:'Comprimé', dosage:'100mg', laboratoireFabricant:'Bayer' },
  { nomCommercial:'Digoxine 0.25mg', dci:'Digoxine', classeTherapeutique:'Cardiotonique', forme:'Comprimé', dosage:'0.25mg', laboratoireFabricant:'GSK' },
  { nomCommercial:'Simvastatine 20mg', dci:'Simvastatine', classeTherapeutique:'Hypolipémiant', forme:'Comprimé', dosage:'20mg', laboratoireFabricant:'MSD' },
  { nomCommercial:'Atorvastatine 40mg', dci:'Atorvastatine', classeTherapeutique:'Hypolipémiant', forme:'Comprimé', dosage:'40mg', laboratoireFabricant:'Pfizer' },
  { nomCommercial:'Colchicine 1mg', dci:'Colchicine', classeTherapeutique:'Antigoutte', forme:'Comprimé', dosage:'1mg', laboratoireFabricant:'Mayoly' },
  { nomCommercial:'Allopurinol 300mg', dci:'Allopurinol', classeTherapeutique:'Hypo-uricemiant', forme:'Comprimé', dosage:'300mg', laboratoireFabricant:'GSK' },
  // ── Respiratoire ──────────────────────────────────────────
  { nomCommercial:'Salbutamol aerosol 100mcg', dci:'Salbutamol', classeTherapeutique:'Bronchodilatateur', forme:'Aérosol', dosage:'100mcg/dose', laboratoireFabricant:'GSK' },
  { nomCommercial:'Beclomethasone 250mcg', dci:'Beclomethasone', classeTherapeutique:'Corticoïde inhalé', forme:'Aérosol', dosage:'250mcg/dose', laboratoireFabricant:'GSK' },
  { nomCommercial:'Theophylline 200mg', dci:'Theophylline', classeTherapeutique:'Bronchodilatateur', forme:'Comprimé LP', dosage:'200mg', laboratoireFabricant:'UCB' },
  { nomCommercial:'N-Acetylcysteine 200mg', dci:'N-Acetylcysteine', classeTherapeutique:'Mucolytique', forme:'Sachet', dosage:'200mg', laboratoireFabricant:'Zambon' },
  { nomCommercial:'Codeine sirop 15mg/5mL', dci:'Codeine phosphate', classeTherapeutique:'Antitussif', forme:'Sirop', dosage:'15mg/5mL', laboratoireFabricant:'Sanofi' },
  // ── Neurologie ────────────────────────────────────────────
  { nomCommercial:'Diazepam 5mg', dci:'Diazepam', classeTherapeutique:'Anxiolytique/Antiépileptique', forme:'Comprimé', dosage:'5mg', laboratoireFabricant:'Roche' },
  { nomCommercial:'Phenobarbital 100mg', dci:'Phenobarbital', classeTherapeutique:'Antiépileptique', forme:'Comprimé', dosage:'100mg', laboratoireFabricant:'Sanofi' },
  { nomCommercial:'Carbamazepine 200mg', dci:'Carbamazepine', classeTherapeutique:'Antiépileptique', forme:'Comprimé', dosage:'200mg', laboratoireFabricant:'Novartis' },
  { nomCommercial:'Haloperidol 5mg', dci:'Haloperidol', classeTherapeutique:'Antipsychotique', forme:'Comprimé', dosage:'5mg', laboratoireFabricant:'J&J' },
  { nomCommercial:'Amitriptyline 25mg', dci:'Amitriptyline', classeTherapeutique:'Antidépresseur', forme:'Comprimé', dosage:'25mg', laboratoireFabricant:'MSD' },
  { nomCommercial:'Chlorpromazine 100mg', dci:'Chlorpromazine', classeTherapeutique:'Antipsychotique', forme:'Comprimé', dosage:'100mg', laboratoireFabricant:'Sanofi' },
  // ── Gyneco/Obstetrique ─────────────────────────────────────
  { nomCommercial:'Oxytocine 5UI', dci:'Oxytocine', classeTherapeutique:'Utérotonique', forme:'Injectable', dosage:'5UI/mL', laboratoireFabricant:'Novartis' },
  { nomCommercial:'Misoprostol 200mcg', dci:'Misoprostol', classeTherapeutique:'Utérotonique', forme:'Comprimé', dosage:'200mcg', laboratoireFabricant:'Pfizer' },
  { nomCommercial:'Ergometrine 0.5mg', dci:'Ergometrine', classeTherapeutique:'Utérotonique', forme:'Injectable', dosage:'0.5mg', laboratoireFabricant:'Novartis' },
  { nomCommercial:'Contraceptif oral combine', dci:'Ethinylestradiol/Levonorgestrel', classeTherapeutique:'Contraceptif', forme:'Comprimé', dosage:'30/150mcg', laboratoireFabricant:'Bayer' },
  // ── Antituberculeux ───────────────────────────────────────
  { nomCommercial:'Rifampicine 150mg', dci:'Rifampicine', classeTherapeutique:'Antituberculeux', forme:'Gélule', dosage:'150mg', laboratoireFabricant:'Sanofi' },
  { nomCommercial:'Isoniazide 100mg', dci:'Isoniazide', classeTherapeutique:'Antituberculeux', forme:'Comprimé', dosage:'100mg', laboratoireFabricant:'Sanofi' },
  { nomCommercial:'RHZE 150/75/400/275mg', dci:'Rifampicine/Isoniazide/Pyrazinamide/Ethambutol', classeTherapeutique:'Antituberculeux combiné', forme:'Comprimé', dosage:'150/75/400/275mg', laboratoireFabricant:'Cipla' },
  // ── Urgences/Perfusions ────────────────────────────────────
  { nomCommercial:'Serum physiologique 0.9% 500mL', dci:'NaCl', classeTherapeutique:'Soluté de remplissage', forme:'Perfusion', dosage:'0.9%', laboratoireFabricant:'Fresenius' },
  { nomCommercial:'Ringer Lactate 500mL', dci:'Solution de Ringer', classeTherapeutique:'Soluté de remplissage', forme:'Perfusion', dosage:'500mL', laboratoireFabricant:'Fresenius' },
  { nomCommercial:'Glucose 5% 500mL', dci:'Glucose', classeTherapeutique:'Soluté glucosé', forme:'Perfusion', dosage:'5%', laboratoireFabricant:'Fresenius' },
  { nomCommercial:'Glucose 50% 50mL', dci:'Glucose hypertonique', classeTherapeutique:'Soluté glucosé', forme:'Injectable', dosage:'50%', laboratoireFabricant:'Fresenius' },
  { nomCommercial:'Adrenaline 1mg/mL', dci:'Adrenaline', classeTherapeutique:'Vasopresseur', forme:'Injectable', dosage:'1mg/mL', laboratoireFabricant:'Sanofi' },
  { nomCommercial:'Atropine 1mg injectable', dci:'Atropine', classeTherapeutique:'Anticholinergique', forme:'Injectable', dosage:'1mg', laboratoireFabricant:'Aguettant' },
  // ── Dermatologie ─────────────────────────────────────────
  { nomCommercial:'Betamethasone creme 0.1%', dci:'Betamethasone', classeTherapeutique:'Corticoïde topique', forme:'Crème', dosage:'0.1%', laboratoireFabricant:'GSK' },
  { nomCommercial:'Hydrocortisone creme 1%', dci:'Hydrocortisone', classeTherapeutique:'Corticoïde topique', forme:'Crème', dosage:'1%', laboratoireFabricant:'Sanofi' },
  { nomCommercial:'Permethrine creme 5%', dci:'Permethrine', classeTherapeutique:'Antiparasitaire topique', forme:'Crème', dosage:'5%', laboratoireFabricant:'GSK' },
  // ── Ophtalmologie ─────────────────────────────────────────
  { nomCommercial:'Ciprofloxacine collyre 0.3%', dci:'Ciprofloxacine', classeTherapeutique:'Antibiotique ophtalmique', forme:'Collyre', dosage:'0.3%', laboratoireFabricant:'Alcon' },
  { nomCommercial:'Timolol collyre 0.5%', dci:'Timolol', classeTherapeutique:'Antiglaucomateux', forme:'Collyre', dosage:'0.5%', laboratoireFabricant:'MSD' },
  { nomCommercial:'Loratadine 10mg', dci:'Loratadine', classeTherapeutique:'Antihistaminique', forme:'Comprimé', dosage:'10mg', laboratoireFabricant:'Schering' },
  { nomCommercial:'Cetirizine 10mg', dci:'Cetirizine', classeTherapeutique:'Antihistaminique', forme:'Comprimé', dosage:'10mg', laboratoireFabricant:'UCB' },
];

const EXAMENS = [
  // Hématologie
  { nom:'Numération Formule Sanguine (NFS)', codeAzamed:'HEMA-001', categorie:'Hématologie', description:'Analyse complète des cellules sanguines' },
  { nom:'Groupe sanguin ABO et Rhesus', codeAzamed:'HEMA-002', categorie:'Hématologie', description:'Détermination du groupe sanguin' },
  { nom:"Taux d'hémoglobine", codeAzamed:'HEMA-003', categorie:'Hématologie', description:"Mesure du taux d'hémoglobine" },
  { nom:'TP/INR', codeAzamed:'HEMA-004', categorie:'Hématologie', description:'Temps de prothrombine / INR' },
  { nom:'TCA', codeAzamed:'HEMA-005', categorie:'Hématologie', description:'Temps de céphaline activée' },
  { nom:'VS (Vitesse de sedimentation)', codeAzamed:'HEMA-006', categorie:'Hématologie', description:"Marqueur d'inflammation" },
  { nom:'Frottis sanguin', codeAzamed:'HEMA-007', categorie:'Hématologie', description:'Examen microscopique des cellules sanguines' },
  { nom:'Numeration plaquettaire', codeAzamed:'HEMA-008', categorie:'Hématologie', description:'Comptage des plaquettes' },
  { nom:'Reticulocytes', codeAzamed:'HEMA-009', categorie:'Hématologie', description:'Jeunes globules rouges' },
  // Biochimie
  { nom:'Glycemie a jeun', codeAzamed:'BIOC-001', categorie:'Biochimie', description:'Taux de glucose sanguin a jeun' },
  { nom:'Glycemie post-prandiale', codeAzamed:'BIOC-002', categorie:'Biochimie', description:'Taux de glucose 2h apres repas' },
  { nom:'HbA1c (Hemoglobine glyquee)', codeAzamed:'BIOC-003', categorie:'Biochimie', description:'Controle du diabete sur 3 mois' },
  { nom:'Creatinine serique', codeAzamed:'BIOC-004', categorie:'Biochimie', description:'Evaluation de la fonction renale' },
  { nom:'Uree sanguine', codeAzamed:'BIOC-005', categorie:'Biochimie', description:'Evaluation de la fonction renale' },
  { nom:'Acide urique', codeAzamed:'BIOC-006', categorie:'Biochimie', description:"Dosage de l'acide urique" },
  { nom:'ALAT/SGPT', codeAzamed:'BIOC-007', categorie:'Biochimie', description:'Enzyme hepatique' },
  { nom:'ASAT/SGOT', codeAzamed:'BIOC-008', categorie:'Biochimie', description:'Enzyme hepatique' },
  { nom:'Bilirubine totale et directe', codeAzamed:'BIOC-009', categorie:'Biochimie', description:'Evaluation de la fonction hepatique' },
  { nom:'Phosphatases alcalines', codeAzamed:'BIOC-010', categorie:'Biochimie', description:'Enzyme hepatique/osseuse' },
  { nom:'Gamma GT', codeAzamed:'BIOC-011', categorie:'Biochimie', description:'Enzyme hepatique' },
  { nom:'Cholesterol total', codeAzamed:'BIOC-012', categorie:'Biochimie', description:'Bilan lipidique' },
  { nom:'HDL cholesterol', codeAzamed:'BIOC-013', categorie:'Biochimie', description:'Bon cholesterol' },
  { nom:'LDL cholesterol', codeAzamed:'BIOC-014', categorie:'Biochimie', description:'Mauvais cholesterol' },
  { nom:'Triglycerides', codeAzamed:'BIOC-015', categorie:'Biochimie', description:'Bilan lipidique' },
  { nom:'Ionogramme sanguin (Na, K, Cl)', codeAzamed:'BIOC-016', categorie:'Biochimie', description:'Electrolytes sanguins' },
  { nom:'Calcemie', codeAzamed:'BIOC-017', categorie:'Biochimie', description:'Taux de calcium sanguin' },
  { nom:'CRP (Proteine C reactive)', codeAzamed:'BIOC-018', categorie:'Biochimie', description:"Marqueur d'inflammation" },
  { nom:'Procalcitonine', codeAzamed:'BIOC-019', categorie:'Biochimie', description:"Marqueur d'infection bacterienne" },
  { nom:'PSA (Antigene prostatique specifique)', codeAzamed:'BIOC-020', categorie:'Biochimie', description:'Depistage cancer de la prostate' },
  { nom:'AFP (Alpha-foetoproteine)', codeAzamed:'BIOC-021', categorie:'Biochimie', description:'Marqueur tumoral hepatique' },
  { nom:'CA 125', codeAzamed:'BIOC-022', categorie:'Biochimie', description:'Marqueur tumoral ovarien' },
  { nom:'CA 19-9', codeAzamed:'BIOC-023', categorie:'Biochimie', description:'Marqueur tumoral pancreas/colon' },
  { nom:'ACE (Antigene carcinoembryonnaire)', codeAzamed:'BIOC-024', categorie:'Biochimie', description:'Marqueur tumoral digestif' },
  { nom:'Troponine', codeAzamed:'BIOC-025', categorie:'Biochimie', description:'Marqueur de lesion cardiaque' },
  { nom:'Amylase', codeAzamed:'BIOC-026', categorie:'Biochimie', description:'Enzyme pancreatique' },
  { nom:'Lipase', codeAzamed:'BIOC-027', categorie:'Biochimie', description:'Enzyme pancreatique' },
  { nom:'Ferritine', codeAzamed:'BIOC-028', categorie:'Biochimie', description:'Reserves en fer' },
  { nom:'Proteines totales', codeAzamed:'BIOC-029', categorie:'Biochimie', description:'Dosage des proteines seriques' },
  { nom:'Albumine serique', codeAzamed:'BIOC-030', categorie:'Biochimie', description:"Dosage de l'albumine" },
  // Serologie
  { nom:'Test VIH (ELISA)', codeAzamed:'SERO-001', categorie:'Sérologie', description:'Depistage du VIH/SIDA' },
  { nom:'Charge virale VIH', codeAzamed:'SERO-002', categorie:'Sérologie', description:'Quantification du virus VIH' },
  { nom:'CD4', codeAzamed:'SERO-003', categorie:'Sérologie', description:'Numeration des lymphocytes CD4' },
  { nom:'Ag HBs (Hepatite B)', codeAzamed:'SERO-004', categorie:'Sérologie', description:'Depistage hepatite B' },
  { nom:'Ac Anti-HBs', codeAzamed:'SERO-005', categorie:'Sérologie', description:'Anticorps protecteurs hepatite B' },
  { nom:'Charge virale hepatite B', codeAzamed:'SERO-006', categorie:'Sérologie', description:'Quantification virus hepatite B' },
  { nom:'Ac Anti-VHC (Hepatite C)', codeAzamed:'SERO-007', categorie:'Sérologie', description:'Depistage hepatite C' },
  { nom:'Charge virale hepatite C', codeAzamed:'SERO-008', categorie:'Sérologie', description:'Quantification virus hepatite C' },
  { nom:'TPHA/VDRL (Syphilis)', codeAzamed:'SERO-009', categorie:'Sérologie', description:'Depistage de la syphilis' },
  { nom:'Toxoplasmose IgG/IgM', codeAzamed:'SERO-010', categorie:'Sérologie', description:'Serologie toxoplasmose' },
  { nom:'Rubeole IgG/IgM', codeAzamed:'SERO-011', categorie:'Sérologie', description:'Serologie rubeole' },
  { nom:'CMV IgG/IgM', codeAzamed:'SERO-012', categorie:'Sérologie', description:'Cytomegalovirus' },
  { nom:'Widal (Fievre typhoide)', codeAzamed:'SERO-013', categorie:'Sérologie', description:'Test de Widal pour typhoide' },
  { nom:'Brucella (Wright)', codeAzamed:'SERO-014', categorie:'Sérologie', description:'Depistage brucellose' },
  { nom:'Facteur rhumatoide (FR)', codeAzamed:'SERO-015', categorie:'Sérologie', description:'Polyarthrite rhumatoide' },
  { nom:'Test de grossesse (Beta HCG)', codeAzamed:'SERO-016', categorie:'Sérologie', description:'Dosage de la HCG' },
  // Parasitologie
  { nom:'Goutte epaisse / TDR Paludisme', codeAzamed:'PARA-001', categorie:'Parasitologie', description:'Depistage du paludisme' },
  { nom:'Examen parasitologique des selles (EPS)', codeAzamed:'PARA-002', categorie:'Parasitologie', description:'Recherche de parasites intestinaux' },
  { nom:'Scotch test anal (oxyures)', codeAzamed:'PARA-003', categorie:'Parasitologie', description:"Recherche d'oxyures" },
  { nom:'Recherche de filaires', codeAzamed:'PARA-004', categorie:'Parasitologie', description:'Depistage filariose' },
  // Bacteriologie
  { nom:'ECBU (Examen cyto-bacteriologique des urines)', codeAzamed:'BACT-001', categorie:'Bactériologie', description:'Analyse urinaire complete' },
  { nom:'Hemoculture', codeAzamed:'BACT-002', categorie:'Bactériologie', description:'Culture du sang pour bacteries' },
  { nom:'Antibiogramme', codeAzamed:'BACT-003', categorie:'Bactériologie', description:'Sensibilite aux antibiotiques' },
  { nom:'BK crachats (Bacille de Koch)', codeAzamed:'BACT-004', categorie:'Bactériologie', description:'Recherche tuberculose' },
  { nom:'Prelevement vaginal/uretral', codeAzamed:'BACT-005', categorie:'Bactériologie', description:'Analyse des secretions genitales' },
  { nom:'LCR (Ponction lombaire)', codeAzamed:'BACT-006', categorie:'Bactériologie', description:'Analyse du liquide cephalorachidien' },
  { nom:'Culture crachat', codeAzamed:'BACT-007', categorie:'Bactériologie', description:'Culture microbiologique des crachats' },
  // Urologie
  { nom:'Bandelette urinaire', codeAzamed:'URO-001', categorie:'Urologie', description:'Analyse rapide des urines' },
  { nom:'Proteinurie de 24h', codeAzamed:'URO-002', categorie:'Urologie', description:'Dosage des proteines dans les urines sur 24h' },
  { nom:'Microalbuminurie', codeAzamed:'URO-003', categorie:'Urologie', description:"Petites quantites d'albumine dans les urines" },
  { nom:'Clairance creatinine', codeAzamed:'URO-004', categorie:'Urologie', description:'Filtration glomerulaire' },
  // Hormonologie
  { nom:'TSH (Thyreostimuline)', codeAzamed:'HORM-001', categorie:'Hormonologie', description:'Fonction thyroidienne' },
  { nom:'T3 libre', codeAzamed:'HORM-002', categorie:'Hormonologie', description:'Hormone thyroidienne T3' },
  { nom:'T4 libre', codeAzamed:'HORM-003', categorie:'Hormonologie', description:'Hormone thyroidienne T4' },
  { nom:'Cortisol', codeAzamed:'HORM-004', categorie:'Hormonologie', description:'Hormone surrenalienne' },
  { nom:'FSH/LH', codeAzamed:'HORM-005', categorie:'Hormonologie', description:'Hormones de la fertilite' },
  { nom:'Oestradiol', codeAzamed:'HORM-006', categorie:'Hormonologie', description:'Hormone feminine' },
  { nom:'Progesterone', codeAzamed:'HORM-007', categorie:'Hormonologie', description:'Hormone de la grossesse' },
  { nom:'Testosterone', codeAzamed:'HORM-008', categorie:'Hormonologie', description:'Hormone masculine' },
  { nom:'Prolactine', codeAzamed:'HORM-009', categorie:'Hormonologie', description:'Hormone de la lactation' },
  { nom:'Beta HCG quantitatif', codeAzamed:'HORM-010', categorie:'Hormonologie', description:'Suivi de grossesse' },
  // Imagerie
  { nom:'Radiographie thoracique', codeAzamed:'IMG-001', categorie:'Imagerie', description:'Radiographie du thorax' },
  { nom:'Radiographie abdomen (ASP)', codeAzamed:'IMG-002', categorie:'Imagerie', description:"Radiographie de l'abdomen" },
  { nom:'Radiographie osseuse', codeAzamed:'IMG-003', categorie:'Imagerie', description:'Radiographie des os et articulations' },
  { nom:'Echographie abdominale', codeAzamed:'IMG-004', categorie:'Imagerie', description:"Echographie de l'abdomen" },
  { nom:'Echographie pelvienne', codeAzamed:'IMG-005', categorie:'Imagerie', description:'Echographie du pelvis' },
  { nom:'Echographie obstetricale', codeAzamed:'IMG-006', categorie:'Imagerie', description:'Echographie de grossesse' },
  { nom:'Echographie cardiaque (Echo-coeur)', codeAzamed:'IMG-007', categorie:'Imagerie', description:'Echocardiographie' },
  { nom:'Echographie thyroidienne', codeAzamed:'IMG-008', categorie:'Imagerie', description:'Echographie de la thyroide' },
  { nom:'Mammographie', codeAzamed:'IMG-009', categorie:'Imagerie', description:'Radiographie des seins' },
  { nom:'Scanner (TDM) cerebral', codeAzamed:'IMG-010', categorie:'Imagerie', description:'Tomodensitometrie du cerveau' },
  { nom:'Scanner thoracique', codeAzamed:'IMG-011', categorie:'Imagerie', description:'Tomodensitometrie du thorax' },
  { nom:'Scanner abdominal', codeAzamed:'IMG-012', categorie:'Imagerie', description:"Tomodensitometrie de l'abdomen" },
  { nom:'IRM cerebrale', codeAzamed:'IMG-013', categorie:'Imagerie', description:'IRM du cerveau' },
  { nom:'IRM rachidienne', codeAzamed:'IMG-014', categorie:'Imagerie', description:'IRM de la colonne vertebrale' },
  { nom:'Panoramique dentaire', codeAzamed:'IMG-015', categorie:'Imagerie', description:'Radiographie dentaire panoramique' },
  // Anatomopathologie
  { nom:'Frottis cervico-vaginal (FCV)', codeAzamed:'ANAT-001', categorie:'Anatomopathologie', description:'Depistage cancer du col uterin' },
  { nom:'Biopsie hepatique', codeAzamed:'ANAT-002', categorie:'Anatomopathologie', description:'Prelevement et analyse du foie' },
  { nom:'Biopsie ganglionnaire', codeAzamed:'ANAT-003', categorie:'Anatomopathologie', description:"Analyse d'un ganglion lymphatique" },
  { nom:'Biopsie cutanee', codeAzamed:'ANAT-004', categorie:'Anatomopathologie', description:"Analyse d'un fragment de peau" },
  { nom:'Biopsie prostatique', codeAzamed:'ANAT-005', categorie:'Anatomopathologie', description:'Prelevement de tissu prostatique' },
  { nom:'Cytologie des liquides', codeAzamed:'ANAT-006', categorie:'Anatomopathologie', description:'Analyse cytologique des epanchements' },
];

const SERVICES = [
  // Médecine générale
  { nom:'Consultation medecine generale', categorie:'Médecine générale', description:'Consultation medicale generaliste' },
  { nom:'Consultation urgence', categorie:'Médecine générale', description:'Prise en charge des urgences medicales' },
  { nom:'Visite a domicile', categorie:'Médecine générale', description:'Consultation medicale a domicile' },
  { nom:'Vaccination adulte et enfant', categorie:'Médecine générale', description:'Programme de vaccination' },
  { nom:'Planification familiale', categorie:'Médecine générale', description:'Contraception et conseil familial' },
  { nom:'Certificat medical', categorie:'Médecine générale', description:'Delivrance de certificats medicaux' },
  { nom:'Medecine du travail', categorie:'Médecine générale', description:'Sante en milieu professionnel' },
  // Spécialités médicales
  { nom:'Cardiologie', categorie:'Spécialité médicale', description:'Maladies du coeur et des vaisseaux' },
  { nom:'Pneumologie', categorie:'Spécialité médicale', description:'Maladies respiratoires' },
  { nom:'Neurologie', categorie:'Spécialité médicale', description:'Maladies du systeme nerveux' },
  { nom:'Gastro-enterologie', categorie:'Spécialité médicale', description:'Maladies digestives' },
  { nom:'Endocrinologie/Diabetologie', categorie:'Spécialité médicale', description:'Diabete, thyroide, hormones' },
  { nom:'Nephrologie', categorie:'Spécialité médicale', description:'Maladies renales' },
  { nom:'Rhumatologie', categorie:'Spécialité médicale', description:'Maladies articulaires et osseuses' },
  { nom:'Hematologie', categorie:'Spécialité médicale', description:'Maladies du sang' },
  { nom:'Infectiologie/VIH', categorie:'Spécialité médicale', description:'Maladies infectieuses et VIH' },
  { nom:'Oncologie medicale', categorie:'Spécialité médicale', description:'Cancer et chimiotherapie' },
  { nom:'Dermatologie', categorie:'Spécialité médicale', description:'Maladies de la peau' },
  { nom:'Ophtalmologie', categorie:'Spécialité médicale', description:'Maladies des yeux' },
  { nom:'ORL (Oto-rhino-laryngologie)', categorie:'Spécialité médicale', description:'Oreilles, nez, gorge' },
  { nom:'Stomatologie/Dentisterie', categorie:'Spécialité médicale', description:'Soins dentaires' },
  { nom:'Psychiatrie', categorie:'Spécialité médicale', description:'Sante mentale' },
  { nom:'Medecine interne', categorie:'Spécialité médicale', description:'Pathologies complexes multisystemiques' },
  { nom:'Urologie', categorie:'Spécialité médicale', description:'Maladies des voies urinaires et de la prostate' },
  { nom:'Medecine physique/Reeducation', categorie:'Spécialité médicale', description:'Reeducation fonctionnelle et kinesitherapie' },
  { nom:'Psychologie clinique', categorie:'Spécialité médicale', description:'Suivi psychologique et therapies' },
  // Spécialités chirurgicales
  { nom:'Chirurgie generale', categorie:'Spécialité chirurgicale', description:"Chirurgie de l'abdomen et organes" },
  { nom:'Chirurgie orthopedique/Traumatologie', categorie:'Spécialité chirurgicale', description:'Os, articulations, fractures' },
  { nom:'Neurochirurgie', categorie:'Spécialité chirurgicale', description:'Chirurgie du cerveau et de la colonne' },
  { nom:'Chirurgie cardiovasculaire', categorie:'Spécialité chirurgicale', description:'Chirurgie du coeur et des vaisseaux' },
  { nom:'Chirurgie urologique', categorie:'Spécialité chirurgicale', description:'Chirurgie des voies urinaires' },
  { nom:'Chirurgie plastique/reconstructrice', categorie:'Spécialité chirurgicale', description:'Chirurgie esthetique et reconstructrice' },
  { nom:'Chirurgie pediatrique', categorie:'Spécialité chirurgicale', description:"Chirurgie de l'enfant" },
  { nom:'Chirurgie maxillo-faciale', categorie:'Spécialité chirurgicale', description:'Chirurgie buccale et faciale' },
  { nom:'Chirurgie ORL', categorie:'Spécialité chirurgicale', description:'Chirurgie ORL' },
  // Gynécologie-Obstétrique
  { nom:'Consultation gynecologique', categorie:'Gynécologie-Obstétrique', description:'Suivi gynecologique de la femme' },
  { nom:'Suivi de grossesse (CPN)', categorie:'Gynécologie-Obstétrique', description:'Consultations prenatales' },
  { nom:'Accouchement normal', categorie:'Gynécologie-Obstétrique', description:'Accouchement par voie basse' },
  { nom:'Accouchement par cesarienne', categorie:'Gynécologie-Obstétrique', description:'Accouchement chirurgical' },
  { nom:'Soins post-partum (CPON)', categorie:'Gynécologie-Obstétrique', description:'Soins apres accouchement' },
  { nom:'Colposcopie', categorie:'Gynécologie-Obstétrique', description:"Examen du col de l'uterus" },
  { nom:'Hystéroscopie', categorie:'Gynécologie-Obstétrique', description:"Examen de l'interieur de l'uterus" },
  // Pédiatrie
  { nom:'Consultation pediatrique', categorie:'Pédiatrie', description:"Soins medicaux de l'enfant" },
  { nom:'Suivi de croissance enfant', categorie:'Pédiatrie', description:"Surveillance de la croissance de l'enfant" },
  { nom:'Vaccination enfant (PEV)', categorie:'Pédiatrie', description:'Programme elargi de vaccination' },
  { nom:'Neonatologie', categorie:'Pédiatrie', description:'Soins du nouveau-ne' },
  { nom:'Urgences pediatriques', categorie:'Pédiatrie', description:"Prise en charge urgences chez l'enfant" },
  { nom:'Nutrition pediatrique', categorie:'Pédiatrie', description:"Malnutrition et alimentation de l'enfant" },
  // Plateau technique
  { nom:'Reanimation medicale', categorie:'Plateau technique', description:'Reanimation medicale et chirurgicale' },
  { nom:'Soins intensifs (ICU)', categorie:'Plateau technique', description:'Unite de soins intensifs' },
  { nom:'Bloc operatoire', categorie:'Plateau technique', description:"Salle d'operation chirurgicale" },
  { nom:'Anesthesie generale', categorie:'Plateau technique', description:'Anesthesie pour chirurgie' },
  { nom:'Anesthesie locoregionale', categorie:'Plateau technique', description:'Peridurale, rachianesthesie' },
  { nom:'Hemodialyse', categorie:'Plateau technique', description:'Rein artificiel pour insuffisance renale' },
  { nom:'Oxygenotherapie', categorie:'Plateau technique', description:"Administration d'oxygene medical" },
  { nom:'Transfusion sanguine', categorie:'Plateau technique', description:'Transfusion de produits sanguins' },
  { nom:'Electrocardiogramme (ECG)', categorie:'Plateau technique', description:'Enregistrement activite electrique cardiaque' },
  { nom:'Holter ECG 24h', categorie:'Plateau technique', description:'ECG ambulatoire sur 24 heures' },
  { nom:'Spirometrie/EFR', categorie:'Plateau technique', description:'Exploration fonctionnelle respiratoire' },
  { nom:'Fibroscopie gastrique (FOGD)', categorie:'Plateau technique', description:'Endoscopie digestive haute' },
  { nom:'Coloscopie', categorie:'Plateau technique', description:'Exploration du colon' },
  { nom:'Bronchoscopie', categorie:'Plateau technique', description:'Exploration des bronches' },
  { nom:'Cystoscopie', categorie:'Plateau technique', description:'Exploration de la vessie' },
  // Hospitalisation
  { nom:'Hospitalisation medecine', categorie:'Hospitalisation', description:'Hospitalisation en service de medecine' },
  { nom:'Hospitalisation chirurgie', categorie:'Hospitalisation', description:'Hospitalisation en service de chirurgie' },
  { nom:'Hospitalisation maternite', categorie:'Hospitalisation', description:'Hospitalisation en maternite' },
  { nom:'Hospitalisation pediatrie', categorie:'Hospitalisation', description:"Hospitalisation d'enfants" },
  { nom:'Hospitalisation soins intensifs', categorie:'Hospitalisation', description:'Sejour en reanimation' },
  { nom:'Hospitalisation psychiatrie', categorie:'Hospitalisation', description:'Hospitalisation en psychiatrie' },
  // Programmes Cameroun
  { nom:'Programme VIH/SIDA (PTME)', categorie:'Programmes Cameroun', description:'Prevention transmission mere-enfant du VIH' },
  { nom:'Programme tuberculose (PNT)', categorie:'Programmes Cameroun', description:'Prise en charge de la tuberculose' },
  { nom:'Programme paludisme', categorie:'Programmes Cameroun', description:'Prevention et traitement du paludisme' },
  { nom:'Depistage cancers', categorie:'Programmes Cameroun', description:'Initiative de prevention des cancers' },
  { nom:'Nutrition therapeutique', categorie:'Programmes Cameroun', description:'Prise en charge malnutrition severe' },
  { nom:'SMI (Sante maternelle et infantile)', categorie:'Programmes Cameroun', description:'Programme de sante mere-enfant' },
  // Prévention
  { nom:'Bilan de sante complet', categorie:'Prévention', description:'Bilan medical annuel complet' },
  { nom:'Depistage diabete', categorie:'Prévention', description:'Depistage precoce du diabete' },
  { nom:'Depistage hypertension', categorie:'Prévention', description:'Mesure et suivi de la tension arterielle' },
  { nom:'Depistage cancer du sein', categorie:'Prévention', description:'Mammographie et auto-examen' },
  { nom:'Depistage cancer du col (FCV)', categorie:'Prévention', description:'Frottis cervico-vaginal de depistage' },
  { nom:'Depistage MST/IST', categorie:'Prévention', description:'Infections sexuellement transmissibles' },
  { nom:'Conseils hygiene et nutrition', categorie:'Prévention', description:'Education therapeutique' },
];

module.exports = { MEDICAMENTS, EXAMENS, SERVICES };
